#!/bin/sh
# Generate build.ninja for Ur/Web.
# Called by configure with variables: srcdir builddir prefix BIN LIB SRCLIB INCLUDE
# CC MLTON NINJA BEARSSL_* LIBUNISTRING_* PTHREAD_* BEARSSL_USE_VENDOR

: "${srcdir:=.}"
: "${builddir:=.}"
: "${prefix:=/usr/local}"
: "${BIN:=$prefix/bin}"
: "${LIB:=$prefix/lib}"
: "${SRCLIB:=$prefix/lib/urweb}"
: "${INCLUDE:=$prefix/include/urweb}"
: "${CC:=gcc}"
: "${MLTON:=mlton}"
: "${BEARSSL_INCLUDES:=}"
: "${BEARSSL_LDFLAGS:=}"
: "${BEARSSL_LIBS:=-lbearssl}"
: "${BEARSSL_USE_VENDOR:=0}"
: "${LIBUNISTRING_INCLUDES:=}"
: "${LIBUNISTRING_LIBS:=-lunistring}"
: "${PTHREAD_CFLAGS:=-pthread}"
: "${PTHREAD_LIBS:=-pthread}"

case "$(uname -s)" in
  Darwin*) SHLIB_EXT=".dylib" ;;
  *)       SHLIB_EXT=".so" ;;
esac

# C include path: need config.h from builddir
CPPFLAGS="-I\$builddir/include/urweb -I\$srcdir/include/urweb \$BEARSSL_INCLUDES \$LIBUNISTRING_INCLUDES \$PTHREAD_CFLAGS"
CFLAGS="-Wall -Wunused-parameter -Werror -Wno-format-security -Wno-deprecated-declarations -U_FORTIFY_SOURCE"

cat <<'GENEOF'
# Ur/Web build.ninja - generated by gen_build.ninja.sh

GENEOF

# Emit variables (single-quote in the heredoc prevents expansion; we need the values)
echo "srcdir = $srcdir"
echo "builddir = $builddir"
echo "prefix = $prefix"
echo "BIN = $BIN"
echo "LIB = $LIB"
echo "SRCLIB = $SRCLIB"
echo "INCLUDE = $INCLUDE"
echo "CC = $CC"
echo "MLTON = $MLTON"
echo "BEARSSL_INCLUDES = $BEARSSL_INCLUDES"
echo "BEARSSL_LDFLAGS = $BEARSSL_LDFLAGS"
echo "BEARSSL_LIBS = $BEARSSL_LIBS"
echo "BEARSSL_USE_VENDOR = $BEARSSL_USE_VENDOR"
echo "LIBUNISTRING_INCLUDES = $LIBUNISTRING_INCLUDES"
echo "LIBUNISTRING_LIBS = $LIBUNISTRING_LIBS"
echo "PTHREAD_CFLAGS = $PTHREAD_CFLAGS"
echo "PTHREAD_LIBS = $PTHREAD_LIBS"
echo "CPPFLAGS = -I\$builddir/include/urweb -I\$srcdir/include/urweb \$BEARSSL_INCLUDES \$LIBUNISTRING_INCLUDES \$PTHREAD_CFLAGS"
echo "CFLAGS = $CFLAGS"
echo "SHLIB_EXT = $SHLIB_EXT"
echo ""

cat <<'NINJAEOF'

# Rules
rule mllex
  command = cd $builddir/src && cp $srcdir/src/urweb.lex urweb.mlton.lex && mllex urweb.mlton.lex
  description = mllex urweb.lex -> urweb.mlton.lex.sml

rule mlyacc
  command = cd $builddir/src && cp $srcdir/src/urweb.grm urweb.mlton.grm && mlyacc urweb.mlton.grm
  description = mlyacc urweb.grm

rule mlton
  command = $MLTON -mlb-path-var 'SRC $srcdir/src' -mlb-path-var 'BUILD $builddir/src' -output $out $in
  description = MLton $out

rule mlton_compiler
  command = ( echo ""; echo "[$$(date +%H:%M:%S)] Compiling Ur/Web compiler with MLton (2-3 min)..."; ( while sleep 30; do echo "  [$$(date +%H:%M:%S)] ... still compiling (MLton produces no output until done)"; done ) & p=$$!; trap 'kill $$p 2>/dev/null' EXIT; $MLTON -mlb-path-var 'SRC $srcdir/src' -mlb-path-var 'BUILD $builddir/src' -output $out $in; r=$$?; kill $$p 2>/dev/null; echo "[$$(date +%H:%M:%S)] Compiler build complete."; echo ""; exit $$r )
  description = MLton compiler (2-3 min)
  pool = console

rule cc
  command = $CC $CPPFLAGS $CFLAGS -c $in -o $out
  description = CC $out

rule link_so
  command = $CC -shared $BEARSSL_LDFLAGS $PTHREAD_LIBS -lm $BEARSSL_LIBS $LIBUNISTRING_LIBS -o $out $in
  description = LINK $out

rule run
  command = $in $out
  description = RUN $in

rule gen_mlb
  command = sed -e 's/^\(.*\)\.grm$$/$$(BUILD)\/\1.mlton.grm.sig:\1.mlton.grm.sml/' -e 'y/:/\n/' -e 's/^\(.*\)\.lex$$/$$(BUILD)\/\1.mlton.lex.sml/' $in | cat $srcdir/src/prefix.mlb - $srcdir/src/suffix.mlb > $out
  description = Generate urweb.mlb

rule entities
  command = $in $srcdir/xml/xhtml-lat1.ent $srcdir/xml/xhtml-special.ent $srcdir/xml/xhtml-symbol.ent > $out
  description = Generate entities.sml

# BearSSL (vendored) - only when BEARSSL_USE_VENDOR=1

NINJAEOF

if test "$BEARSSL_USE_VENDOR" = "1"; then
  cat <<'NINJABEAR'
rule build_bearssl
  command = echo "[$$(date +%H:%M:%S)] Building BearSSL..." && make -C $srcdir/vendor/BearSSL 2>&1 | sed 's/^/  /' && echo "[$$(date +%H:%M:%S)] BearSSL done."
  description = Build vendored BearSSL
  pool = console

build bearssl: build_bearssl

NINJABEAR
fi

cat <<'NINJAEOF'

# xml/parse
build $builddir/xml/parse: mlton $srcdir/xml/parse.sml

# xml/entities.sml
build $builddir/xml/entities.sml: entities $builddir/xml/parse

# Lexer/parser
build $builddir/src/urweb.mlton.lex.sml: mllex $srcdir/src/urweb.lex

build $builddir/src/urweb.mlton.grm.sig $builddir/src/urweb.mlton.grm.sml: mlyacc $srcdir/src/urweb.grm

# urweb.mlb (order-only: grm.sig, grm.sml, lex.sml must exist first)
rule gen_mlb2
  command = (echo '$$(SML_LIB)/basis/basis.mlb'; echo '$$(SML_LIB)/basis/mlton.mlb'; echo ''; echo '$$(BUILD)/urweb.mlb'; echo ''; echo 'main.mlton.sml') > $out
  description = Generate compiler.mlb placeholder

# Actually we use the existing compiler.mlb. The urweb.mlb is generated from sources.
rule mk_urweb_mlb
  command = sed -e 's/^\(.*\)\.grm$$/$$(BUILD)\/\1.mlton.grm.sig:\1.mlton.grm.sml/' -e 'y/:/\n/' -e 's/^\(.*\)\.lex$$/$$(BUILD)\/\1.mlton.lex.sml/' $srcdir/src/prefix.mlb $srcdir/src/sources $srcdir/src/suffix.mlb > $out
  description = Generate urweb.mlb

build $builddir/src/urweb.mlb: mk_urweb_mlb $srcdir/src/sources $srcdir/src/prefix.mlb $srcdir/src/suffix.mlb

# bin/urweb (use verbose rule so user knows MLton takes time)
build $builddir/bin/urweb: mlton_compiler $srcdir/src/compiler.mlb | $builddir/src/config.sml $builddir/xml/entities.sml $builddir/src/urweb.mlb

# C object files
NINJAEOF

# C sources for liburweb
CSOURCES="memmem.c crypto.c urweb.c request.c queue.c"
for c in $CSOURCES; do
  echo "build \$builddir/src/c/${c%.c}.o: cc \$srcdir/src/c/$c"
done

# Protocol C sources (http, cgi, fastcgi, static)
PROTOCOLS="http cgi fastcgi static"
for c in $PROTOCOLS; do
  echo "build \$builddir/src/c/${c}.o: cc \$srcdir/src/c/${c}.c"
done

cat <<'NINJAEOF2'

# liburweb (static - we use .a for simplicity; shared libs need more setup)
rule ar
  command = ar crs $out $in
  description = AR $out

NINJAEOF2

OBJS=""
for c in $CSOURCES; do
  OBJS="$OBJS \$builddir/src/c/${c%.c}.o"
done
echo "build \$builddir/src/c/liburweb.a: ar $OBJS"
echo ""
for p in $PROTOCOLS; do
  echo "build \$builddir/src/c/liburweb_${p}.a: ar \$builddir/src/c/${p}.o"
done
echo ""

# Install (DESTDIR supported)
echo "rule install_cmd"
echo "  command = DESTDIR=\"\$\${DESTDIR:-}\" ; mkdir -p \"\$\$DESTDIR$BIN\" \"\$\$DESTDIR$LIB\" \"\$\$DESTDIR$SRCLIB/ur\" \"\$\$DESTDIR$SRCLIB/js\" \"\$\$DESTDIR$INCLUDE\" && install $builddir/bin/urweb \"\$\$DESTDIR$BIN/\" && cp $builddir/src/c/liburweb.a \"\$\$DESTDIR$LIB/\" && cp $builddir/src/c/liburweb_http.a $builddir/src/c/liburweb_cgi.a $builddir/src/c/liburweb_fastcgi.a $builddir/src/c/liburweb_static.a \"\$\$DESTDIR$LIB/\" && cp $srcdir/lib/ur/*.urs \"\$\$DESTDIR$SRCLIB/ur/\" && cp $srcdir/lib/ur/*.ur \"\$\$DESTDIR$SRCLIB/ur/\" && cp $srcdir/lib/js/*.js \"\$\$DESTDIR$SRCLIB/js/\" && cp $srcdir/include/urweb/*.h \"\$\$DESTDIR$INCLUDE/\" && (cp $builddir/include/urweb/config.h \"\$\$DESTDIR$INCLUDE/\" 2>/dev/null || true)"
echo "  description = Install Ur/Web"
echo ""
echo "build install: install_cmd | $builddir/bin/urweb $builddir/src/c/liburweb.a $builddir/src/c/liburweb_http.a $builddir/src/c/liburweb_cgi.a $builddir/src/c/liburweb_fastcgi.a $builddir/src/c/liburweb_static.a"
echo ""

# Uninstall (DESTDIR supported, must match install prefix)
echo "rule uninstall_cmd"
echo "  command = DESTDIR=\"\$\${DESTDIR:-}\" ; rm -f \"\$\$DESTDIR$BIN/urweb\" \"\$\$DESTDIR$LIB/liburweb.a\" \"\$\$DESTDIR$LIB/liburweb_http.a\" \"\$\$DESTDIR$LIB/liburweb_cgi.a\" \"\$\$DESTDIR$LIB/liburweb_fastcgi.a\" \"\$\$DESTDIR$LIB/liburweb_static.a\" && rm -f \"\$\$DESTDIR$SRCLIB/ur/\"*.urs \"\$\$DESTDIR$SRCLIB/ur/\"*.ur \"\$\$DESTDIR$SRCLIB/js/\"*.js \"\$\$DESTDIR$INCLUDE/\"*.h \"\$\$DESTDIR$INCLUDE/config.h\""
echo "  description = Uninstall Ur/Web"
echo ""
echo "build uninstall: uninstall_cmd"
echo ""

# Test (requires bin/urweb, sqlite3, curl)
# pool = console gives direct terminal access so output appears in real time
echo "rule test_cmd"
echo "  command = sh $srcdir/run-tests.sh $srcdir $builddir"
echo "  description = Run tests (demo + 21)"
echo "  pool = console"
echo ""
echo "build test: test_cmd | $builddir/bin/urweb"
echo ""

# Default target
cat <<'NINJAEOF3'
build all: phony $builddir/bin/urweb $builddir/src/c/liburweb.a $builddir/src/c/liburweb_http.a $builddir/src/c/liburweb_cgi.a $builddir/src/c/liburweb_fastcgi.a $builddir/src/c/liburweb_static.a

default all
NINJAEOF3
