//! Auto-generated by scripts/gen_diagnostic_catalog.py — do not hand-edit.

#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DiagnosticId {
    /// Catalog entry 1.
    EmptyPlain = 1,
    /// Catalog entry 2.
    UnboundKindVariable = 2,
    /// Catalog entry 3.
    HintUnboundKindVariable = 3,
    /// Catalog entry 4.
    WildcardDisallowedInSignature = 4,
    /// Catalog entry 5.
    HintWildcardDisallowedInSignature = 5,
    /// Catalog entry 6.
    UnboundConstructorVariable = 6,
    /// Catalog entry 7.
    HintUnboundConstructorVariable = 7,
    /// Catalog entry 8.
    UnboundDatatypeName = 8,
    /// Catalog entry 9.
    HintUnboundDatatypeName = 9,
    /// Catalog entry 10.
    UnboundStructureReference = 10,
    /// Catalog entry 11.
    HintUnboundStructureReference = 11,
    /// Catalog entry 12.
    ConstructorWrongKind = 12,
    /// Catalog entry 13.
    HintConstructorWrongKind = 13,
    /// Catalog entry 14.
    DuplicateRecordFieldName = 14,
    /// Catalog entry 15.
    HintDuplicateRecordFieldName = 15,
    /// Catalog entry 16.
    ProjectionIndexOutOfBounds = 16,
    /// Catalog entry 17.
    HintProjectionIndexOutOfBounds = 17,
    /// Catalog entry 18.
    ProjectionKindMismatch = 18,
    /// Catalog entry 19.
    HintProjectionKindMismatch = 19,
    /// Catalog entry 20.
    ConstructorWildcardDisallowedInSignatureConstructor = 20,
    /// Catalog entry 21.
    HintConstructorWildcardDisallowedInSignatureConstructor = 21,
    /// Catalog entry 22.
    KindOccursCheckFailed = 22,
    /// Catalog entry 23.
    IncompatibleKinds = 23,
    /// Catalog entry 24.
    ScopePreventsKindUnification = 24,
    /// Catalog entry 25.
    NestedKindUnificationFailure = 25,
    /// Catalog entry 26.
    ConstructorOccursCheckFailed = 26,
    /// Catalog entry 27.
    IncompatibleConstructorsUnif = 27,
    /// Catalog entry 28.
    TypeFunctionExplicitnessMismatch = 28,
    /// Catalog entry 29.
    UnexpectedKindForKindofQuery = 29,
    /// Catalog entry 30.
    RecordConstructorUnificationFailure = 30,
    /// Catalog entry 31.
    SuspendedLiftingClash = 31,
    /// Catalog entry 32.
    SubstitutionBlockedByDeepUnification = 32,
    /// Catalog entry 33.
    UnificationLiftingTooDeep = 33,
    /// Catalog entry 34.
    ScopePreventsConstructorUnification = 34,
    /// Catalog entry 35.
    UnboundExpressionVariable = 35,
    /// Catalog entry 36.
    HintUnboundExpressionVariable = 36,
    /// Catalog entry 37.
    UnboundStructureInExpression = 37,
    /// Catalog entry 38.
    HintUnboundStructureInExpression = 38,
    /// Catalog entry 39.
    ExpressionUnificationFailure = 39,
    /// Catalog entry 40.
    HintExpressionUnificationFailure = 40,
    /// Catalog entry 41.
    UnificationVariableObstructsOperation = 41,
    /// Catalog entry 42.
    HintUnificationVariableObstructs = 42,
    /// Catalog entry 43.
    ExpressionWrongForm = 43,
    /// Catalog entry 44.
    HintExpressionWrongForm = 44,
    /// Catalog entry 45.
    IncompatibleConstructorsExpression = 45,
    /// Catalog entry 46.
    HintIncompatibleConstructorsExpression = 46,
    /// Catalog entry 47.
    DuplicatePatternVariable = 47,
    /// Catalog entry 48.
    HintDuplicatePatternVariable = 48,
    /// Catalog entry 49.
    PatternUnificationFailure = 49,
    /// Catalog entry 50.
    HintPatternUnificationFailure = 50,
    /// Catalog entry 51.
    UnboundQualifiedConstructor = 51,
    /// Catalog entry 52.
    HintUnboundQualifiedConstructor = 52,
    /// Catalog entry 53.
    PatternConstructorGivenArgumentButExpectsNone = 53,
    /// Catalog entry 54.
    HintPatternConstructorGivenArgumentButExpectsNone = 54,
    /// Catalog entry 55.
    PatternConstructorExpectsArgumentButNoneGiven = 55,
    /// Catalog entry 56.
    HintPatternConstructorExpectsArgumentButNoneGiven = 56,
    /// Catalog entry 57.
    InexhaustiveCaseAnalysis = 57,
    /// Catalog entry 58.
    DuplicatePatternRecordField = 58,
    /// Catalog entry 59.
    HintDuplicatePatternRecordField = 59,
    /// Catalog entry 60.
    UnresolvableTypeClassInstance = 60,
    /// Catalog entry 61.
    TypeClassWildcardOutOfContext = 61,
    /// Catalog entry 62.
    IllegalRecursiveValueBinding = 62,
    /// Catalog entry 63.
    HintIllegalRecursiveValueBinding = 63,
    /// Catalog entry 64.
    KindUnifiersRemainUndetermined = 64,
    /// Catalog entry 65.
    HintKindUnifiersRemainUndetermined = 65,
    /// Catalog entry 66.
    ConstructorUnifiersRemainUndetermined = 66,
    /// Catalog entry 67.
    HintConstructorUnifiersRemainUndetermined = 67,
    /// Catalog entry 68.
    NonStrictlyPositiveDeclaration = 68,
    /// Catalog entry 69.
    HintNonStrictlyPositiveDeclaration = 69,
    /// Catalog entry 70.
    TypeHoleFoundInternal = 70,
    /// Catalog entry 71.
    UnboundSignatureName = 71,
    /// Catalog entry 72.
    HintUnboundSignatureName = 72,
    /// Catalog entry 73.
    UnmatchedSignatureItem = 73,
    /// Catalog entry 74.
    HintUnmatchedSignatureItem = 74,
    /// Catalog entry 75.
    SignatureItemKindUnificationFailed = 75,
    /// Catalog entry 76.
    SignatureItemConstructorUnificationFailed = 76,
    /// Catalog entry 77.
    SignatureItemDatatypeSpecificationsMismatch = 77,
    /// Catalog entry 78.
    IncompatibleSignatureShapes = 78,
    /// Catalog entry 79.
    WhereClauseFieldUnavailable = 79,
    /// Catalog entry 80.
    HintWhereClauseFieldUnavailable = 80,
    /// Catalog entry 81.
    WhereClauseKindMismatch = 81,
    /// Catalog entry 82.
    SignatureNotValidForInclude = 82,
    /// Catalog entry 83.
    HintSignatureNotValidForInclude = 83,
    /// Catalog entry 84.
    DuplicateConstructorNameInSignature = 84,
    /// Catalog entry 85.
    HintDuplicateConstructorNameInSignature = 85,
    /// Catalog entry 86.
    DuplicateValueNameInSignature = 86,
    /// Catalog entry 87.
    HintDuplicateValueNameInSignature = 87,
    /// Catalog entry 88.
    DuplicateNestedSignatureNameInSignature = 88,
    /// Catalog entry 89.
    HintDuplicateNestedSignatureNameInSignature = 89,
    /// Catalog entry 90.
    DuplicateStructureNameInSignature = 90,
    /// Catalog entry 91.
    HintDuplicateStructureNameInSignature = 91,
    /// Catalog entry 92.
    SignatureNotValidForOpenConstraints = 92,
    /// Catalog entry 93.
    HintSignatureNotValidForOpenConstraints = 93,
    /// Catalog entry 94.
    UnboundStructureVariable = 94,
    /// Catalog entry 95.
    HintUnboundStructureVariable = 95,
    /// Catalog entry 96.
    AppliedNonFunctor = 96,
    /// Catalog entry 97.
    HintAppliedNonFunctor = 97,
    /// Catalog entry 98.
    FunctorRebindingAttempt = 98,
    /// Catalog entry 99.
    HintFunctorRebindingAttempt = 99,
    /// Catalog entry 100.
    StructureNotOpenable = 100,
    /// Catalog entry 101.
    HintStructureNotOpenable = 101,
    /// Catalog entry 102.
    ValTypeKindIsNotType = 102,
    /// Catalog entry 103.
    DuplicateDatatypeConstructorNameInGroup = 103,
    /// Catalog entry 104.
    HintDuplicateDatatypeConstructorNameInGroup = 104,
    /// Catalog entry 105.
    ImportingNonDatatypeAsDatatype = 105,
    /// Catalog entry 106.
    HintImportingNonDatatypeAsDatatype = 106,
    /// Catalog entry 107.
    ElabKindMismatch = 107,
    /// Catalog entry 108.
    ElabUnboundKindVariableTemplate = 108,
    /// Catalog entry 109.
    ElabConstructorRecursionDepth = 109,
    /// Catalog entry 110.
    ElabConstructorAppNonArrow = 110,
    /// Catalog entry 111.
    ElabTupleProjectionOutOfBounds = 111,
    /// Catalog entry 112.
    ElabTupleProjectionNonTuple = 112,
    /// Catalog entry 113.
    ElabUnboundTypeConstructor = 113,
    /// Catalog entry 114.
    ElabUnboundModuleFirst = 114,
    /// Catalog entry 115.
    ElabModuleNonConstSignature = 115,
    /// Catalog entry 116.
    ElabSubModuleNonConstSignature = 116,
    /// Catalog entry 117.
    ElabNotAStructure = 117,
    /// Catalog entry 118.
    ElabUnboundModule = 118,
    /// Catalog entry 119.
    ElabUnboundRelConstructor = 119,
    /// Catalog entry 120.
    ElabUnboundNamedConstructor = 120,
    /// Catalog entry 121.
    ElabApplicationNonArrowKind = 121,
    /// Catalog entry 122.
    ElabKAppNonKFun = 122,
    /// Catalog entry 123.
    ElabTypeMismatch = 123,
    /// Catalog entry 124.
    ElabConstructorExpectsArgument = 124,
    /// Catalog entry 125.
    ElabConstructorDoesNotTakeArgument = 125,
    /// Catalog entry 126.
    ElabUnboundConstructor = 126,
    /// Catalog entry 127.
    ElabExpressionRecursionDepth = 127,
    /// Catalog entry 128.
    ElabApplicationNonFunction = 128,
    /// Catalog entry 129.
    ElabConstructorAppNonTcFun = 129,
    /// Catalog entry 130.
    ElabUnboundVariable = 130,
    /// Catalog entry 131.
    ElabImplicitArgIterationLimit = 131,
    /// Catalog entry 132.
    ElabUnboundDatatype = 132,
    /// Catalog entry 133.
    ElabUnboundSignature = 133,
    /// Catalog entry 134.
    ElabUnboundModuleForSignature = 134,
    /// Catalog entry 135.
    ElabSignatureMismatch = 135,
    /// Catalog entry 136.
    ElabSignatureMissingValue = 136,
    /// Catalog entry 137.
    ElabKindMismatchForSignatureValue = 137,
    /// Catalog entry 138.
    ElabWrongConstructorKindFor = 138,
    /// Catalog entry 139.
    ElabSignatureMissingType = 139,
    /// Catalog entry 140.
    ElabWrongTypeForSignature = 140,
    /// Catalog entry 141.
    ElabSignatureMissingStructure = 141,
    /// Catalog entry 142.
    ElabCannotOpenNonConstModule = 142,
    /// Catalog entry 143.
    ElabUnboundStructure = 143,
    /// Catalog entry 144.
    ElabNoStructureInModule = 144,
    /// Catalog entry 145.
    ElabApplicationNonFunctorStructure = 145,
    /// Catalog entry 146.
    ElabUnresolvedDisjointness = 146,
    /// Catalog entry 147.
    ElabUnresolvedTypeclass = 147,
    /// Catalog entry 148.
    CouldNotReadBasisUrs = 148,
    /// Catalog entry 149.
    CouldNotReadTopUrs = 149,
    /// Catalog entry 150.
    CouldNotReadTopUr = 150,
    /// Catalog entry 151.
    CouldNotReadFfiUrs = 151,
    /// Catalog entry 152.
    CouldNotReadSourceUr = 152,
    /// Catalog entry 153.
    CouldNotReadSignatureUrs = 153,
    /// Catalog entry 154.
    ParserNotLinkedUr = 154,
    /// Catalog entry 155.
    ParserNotLinkedUrs = 155,
    /// Catalog entry 156.
    ParseUrSyntaxFailed = 156,
    /// Catalog entry 157.
    HintParseUrSyntax = 157,
    /// Catalog entry 158.
    ParseUrXmlHeuristicNote = 158,
    /// Catalog entry 159.
    ParseUrsSyntaxFailed = 159,
    /// Catalog entry 160.
    HintParseUrsSyntax = 160,
    /// Catalog entry 161.
    SqlCompatExprFragmentParseFailed = 161,
    /// Catalog entry 162.
    SqlCompatExprFragmentPatternMismatch = 162,
    /// Catalog entry 163.
    SqlCompatExprFragmentDeclMismatch = 163,
    /// Catalog entry 164.
    SqlCompatConFragmentParseFailed = 164,
    /// Catalog entry 165.
    SqlCompatConFragmentDeclMismatch = 165,
    /// Catalog entry 166.
    SqlCompatDynamicFieldMissingBraces = 166,
    /// Catalog entry 167.
    SqlCompatFieldMissingBrace = 167,
    /// Catalog entry 168.
    SqlCompatDynamicSelectFieldMissingBraces = 168,
    /// Catalog entry 169.
    SqlCompatUnsupportedExpression = 169,
    /// Catalog entry 170.
    SqlCompatUnsupportedSelectItem = 170,
    /// Catalog entry 171.
    SqlCompatUnsupportedPlaceholder = 171,
    /// Catalog entry 172.
    SqlCompatLeftJoinMissingOn = 172,
    /// Catalog entry 173.
    SqlCompatJoinMissingOn = 173,
    /// Catalog entry 174.
    SqlCompatSelectMissingFrom = 174,
    /// Catalog entry 175.
    SqlCompatInsertMissingInto = 175,
    /// Catalog entry 176.
    SqlCompatInsertMissingFieldList = 176,
    /// Catalog entry 177.
    SqlCompatInsertFieldListMissingParen = 177,
    /// Catalog entry 178.
    SqlCompatInsertMissingValues = 178,
    /// Catalog entry 179.
    SqlCompatInsertValuesMissingOpenParen = 179,
    /// Catalog entry 180.
    SqlCompatInsertValuesMissingCloseParen = 180,
    /// Catalog entry 181.
    SqlCompatDeleteMissingFrom = 181,
    /// Catalog entry 182.
    SqlCompatDeleteMissingWhere = 182,
    /// Catalog entry 183.
    SqlCompatUpdateMissingSet = 183,
    /// Catalog entry 184.
    SqlCompatUpdateMissingWhere = 184,
    /// Catalog entry 185.
    SqlCompatUpdateAssignmentMissingEquals = 185,
    /// Catalog entry 186.
    ExplifyKindErrorPlaceholder = 186,
    /// Catalog entry 187.
    HintExplifyKindErrorPlaceholder = 187,
    /// Catalog entry 188.
    ExplifyKindMetavarUnknown = 188,
    /// Catalog entry 189.
    HintExplifyKindMetavarUnknown = 189,
    /// Catalog entry 190.
    ExplifyTupleKindMetavarUnknown = 190,
    /// Catalog entry 191.
    HintExplifyTupleKindMetavarUnknown = 191,
    /// Catalog entry 192.
    ExplifyUnexpectedConstructorError = 192,
    /// Catalog entry 193.
    ExplifyConstructorMetavarUnknown = 193,
    /// Catalog entry 194.
    HintExplifyConstructorMetavarUnknown = 194,
    /// Catalog entry 195.
    ExplifyUnexpectedExpressionError = 195,
    /// Catalog entry 196.
    ExplifyExpressionUnificationUnknown = 196,
    /// Catalog entry 197.
    ExplifyTypedHoleRemains = 197,
    /// Catalog entry 198.
    ExplifyLocalValRecShouldBeLifted = 198,
    /// Catalog entry 199.
    ExplifySignatureErrorPlaceholder = 199,
    /// Catalog entry 200.
    HintExplifySignatureErrorPlaceholder = 200,
    /// Catalog entry 201.
    ExplifyStructureErrorPlaceholder = 201,
    /// Catalog entry 202.
    HintExplifyStructureErrorPlaceholder = 202,
    /// Catalog entry 203.
    UnnestRemapFailedInternal = 203,
    /// Catalog entry 204.
    InformationFlowPolicyViolation = 204,
    /// Catalog entry 205.
    HintInformationFlowPolicyViolation = 205,
    /// Catalog entry 206.
    DatabasePolicyMayViolate = 206,
    /// Catalog entry 207.
    HintDatabasePolicyMayViolate = 207,
    /// Catalog entry 208.
    SerializationExcludedTypes = 208,
    /// Catalog entry 209.
    HintSerializationExcludedTypes = 209,
    /// Catalog entry 210.
    ExportNamesUndefinedValue = 210,
    /// Catalog entry 211.
    HintExportNamesUndefinedValue = 211,
    /// Catalog entry 212.
    ExportedHandlerUnsafeTypes = 212,
    /// Catalog entry 213.
    HintExportedHandlerUnsafeTypes = 213,
    /// Catalog entry 214.
    CookieStoresUnmarshallableTypes = 214,
    /// Catalog entry 215.
    HintCookieStoresUnmarshallableTypes = 215,
    /// Catalog entry 216.
    TerminationValRecNotProved = 216,
    /// Catalog entry 217.
    HintTerminationValRecNotProved = 217,
    /// Catalog entry 218.
    RpcInternalMissingTranslation = 218,
    /// Catalog entry 219.
    RpcCodeNotNamedFunction = 219,
    /// Catalog entry 220.
    RpcUndetectedTransactionFunction = 220,
    /// Catalog entry 221.
    ExportDuplicateUrlPrefix = 221,
    /// Catalog entry 222.
    ExportFunctionMultipleModes = 222,
    /// Catalog entry 223.
    ExportFunctionMultipleModesShort = 223,
    /// Catalog entry 224.
    ExportInvalidTagExpression = 224,
    /// Catalog entry 225.
    IoSomethingWrongReadingWriting = 225,
    /// Catalog entry 226.
    LspUnusedValueNeverUsedFromEntry = 226,
    /// Catalog entry 227.
    HintLspUnusedValueNeverUsedFromEntry = 227,
    /// Catalog entry 228.
    LspUnusedValRecNotReachable = 228,
    /// Catalog entry 229.
    HintLspUnusedValRecNotReachable = 229,
    /// Catalog entry 230.
    CjrizeAnonymousFunctionRemains = 230,
    /// Catalog entry 231.
    CjrizeNestedClosureRemains = 231,
    /// Catalog entry 232.
    CjrizeJavaScriptStillPresent = 232,
    /// Catalog entry 233.
    HintCjrizeJavaScriptStillPresent = 233,
    /// Catalog entry 234.
    CjrizeSignalReturnInvalidServer = 234,
    /// Catalog entry 235.
    HintCjrizeSignalReturnInvalidServer = 235,
    /// Catalog entry 236.
    CjrizeSignalBindInvalidServer = 236,
    /// Catalog entry 237.
    HintCjrizeSignalBindInvalidServer = 237,
    /// Catalog entry 238.
    CjrizeSignalSourceInvalidServer = 238,
    /// Catalog entry 239.
    HintCjrizeSignalSourceInvalidServer = 239,
    /// Catalog entry 240.
    CjrizeRpcStillOnServer = 240,
    /// Catalog entry 241.
    HintCjrizeRpcStillOnServer = 241,
    /// Catalog entry 242.
    CjrizeChannelRecvUnsupportedServer = 242,
    /// Catalog entry 243.
    HintCjrizeChannelRecvUnsupportedServer = 243,
    /// Catalog entry 244.
    CjrizeSleepInvalidServer = 244,
    /// Catalog entry 245.
    HintCjrizeSleepInvalidServer = 245,
    /// Catalog entry 246.
    CjrizeSpawnInvalidServer = 246,
    /// Catalog entry 247.
    HintCjrizeSpawnInvalidServer = 247,
    /// Catalog entry 248.
    CjrizeTableConstraintNotSimpleString = 248,
    /// Catalog entry 249.
    HintCjrizeTableConstraintNotSimpleString = 249,
    /// Catalog entry 250.
    MutationTestingBadPlaceholder = 250,
    /// Catalog entry 251.
    CorifyInternalCannotDeclareTypeInFfi = 251,
    /// Catalog entry 252.
    CorifyInternalCannotBindValueInFfi = 252,
    /// Catalog entry 253.
    CorifyInternalCannotBindDataConstructorValueInFfi = 253,
    /// Catalog entry 254.
    CorifyInternalCannotBindDataConstructorInFfi = 254,
    /// Catalog entry 255.
    CorifyStructureNestingStackUnderflow = 255,
    /// Catalog entry 256.
    CorifyInternalCannotBindNestedStructureInFfi = 256,
    /// Catalog entry 257.
    CorifyInternalCannotBindFunctorInFfi = 257,
    /// Catalog entry 258.
    CorifyUnknownStructureIdInPath = 258,
    /// Catalog entry 259.
    CorifyUnknownSubmoduleInPath = 259,
    /// Catalog entry 260.
    CorifyNotValueOrConstructorAtPath = 260,
    /// Catalog entry 261.
    CorifyUnknownImportedDataConstructor = 261,
    /// Catalog entry 262.
    CorifyInternalValBindingExpectedNamed = 262,
    /// Catalog entry 263.
    CorifyNotSubmoduleOrFunctor = 263,
    /// Catalog entry 264.
    CorifyUnknownStructureVariableId = 264,
    /// Catalog entry 265.
    CorifyNonConstFfiSignature = 265,
    /// Catalog entry 266.
    CorifyStructureTooFancyToExport = 266,
    /// Catalog entry 267.
    CorifyBasisMissingForExport = 267,
    /// Catalog entry 268.
    CorifyExportDidNotCorifyToGlobalName = 268,
    /// Catalog entry 269.
    CorifyNonConstSignatureForExport = 269,
    /// Catalog entry 270.
    CorifyWrongOnErrorIdentifier = 270,
    /// Catalog entry 271.
    CorifyFfiNotAtModuleTopLevel = 271,
    /// Catalog entry 272.
    CorifyUnknownStructureId = 272,
    /// Catalog entry 273.
    CorifyUnknownSubmoduleInProjection = 273,
    /// Catalog entry 274.
    CorifyNestedFunctorInApplicationUnsupported = 274,
    /// Catalog entry 275.
    CorifyFunctorApplicationUnsupportedForm = 275,
    /// Catalog entry 276.
    InvalidHtml5DataAttribute = 276,
    /// Catalog entry 277.
    InvalidUrlPassedToBless = 277,
    /// Catalog entry 278.
    InvalidStringPassedToBlessMime = 278,
    /// Catalog entry 279.
    InvalidStringPassedToAtom = 279,
    /// Catalog entry 280.
    InvalidUrlPassedToCssUrl = 280,
    /// Catalog entry 281.
    InvalidStringPassedToProperty = 281,
    /// Catalog entry 282.
    InvalidStringPassedToBlessRequestHeader = 282,
    /// Catalog entry 283.
    InvalidStringPassedToBlessResponseHeader = 283,
    /// Catalog entry 284.
    InvalidStringPassedToBlessEnvVar = 284,
    /// Catalog entry 285.
    InvalidStringPassedToBlessMeta = 285,
    /// Catalog entry 286.
    PathTwoConstraintsSameGeneratedPath = 286,
    /// Catalog entry 287.
    HintPathTwoConstraintsSameGeneratedPath = 287,
    /// Catalog entry 288.
    PathTwoExportsSameUrl = 288,
    /// Catalog entry 289.
    HintPathTwoExportsSameUrl = 289,
    /// Catalog entry 290.
    PathTableOrSequenceDeclaredTwice = 290,
    /// Catalog entry 291.
    HintPathTableOrSequenceDeclaredTwice = 291,
    /// Catalog entry 292.
    PathPrimaryKeyMetadataCollides = 292,
    /// Catalog entry 293.
    HintPathPrimaryKeyMetadataCollides = 293,
    /// Catalog entry 294.
    PathTwoCookiesSharePath = 294,
    /// Catalog entry 295.
    HintPathTwoCookiesSharePath = 295,
    /// Catalog entry 296.
    PathTwoStylesSamePath = 296,
    /// Catalog entry 297.
    HintPathTwoStylesSamePath = 297,
    /// Catalog entry 298.
    ScriptPushProtocolNotPersistent = 298,
    /// Catalog entry 299.
    HintScriptPushProtocolNotPersistent = 299,
    /// Catalog entry 300.
    SideServerCallsClientOnlyFfi = 300,
    /// Catalog entry 301.
    HintSideServerCallsClientOnlyFfi = 301,
    /// Catalog entry 302.
    SqlTablePrimaryKeyNotKnownString = 302,
    /// Catalog entry 303.
    HintSqlTablePrimaryKeyNotKnownString = 303,
    /// Catalog entry 304.
    SqlViewNotPlainString = 304,
    /// Catalog entry 305.
    HintSqlViewNotPlainStringStrcat = 305,
    /// Catalog entry 306.
    HintSqlViewNotPlainStringLiteral = 306,
    /// Catalog entry 307.
    CjrizeFunctionNotExplicitAtCodegen = 307,
    /// Catalog entry 308.
    CjrizeTaskKindNotFullyDetermined = 308,
    /// Catalog entry 309.
    CjrizeInitializerNotFullyDetermined = 309,
    /// Catalog entry 310.
    CorifyUnknownTypeNameInModulePath = 310,
    /// Catalog entry 311.
    CorifyUnknownPatternConstructorId = 311,
    /// Catalog entry 312.
    CorifyUnknownDataConstructorInModulePath = 312,
    /// Catalog entry 313.
    JscompInternalStrcatInvariant = 313,
    /// Catalog entry 314.
    JscompUnurlifyUnknownType = 314,
    /// Catalog entry 315.
    JscompUnsupportedFfiValueInJs = 315,
    /// Catalog entry 316.
    JscompUnsupportedFfiCallInJs = 316,
    /// Catalog entry 317.
    JscompUnknownUnaryOperatorInJs = 317,
    /// Catalog entry 318.
    JscompUnknownBinaryOperatorInJs = 318,
    /// Catalog entry 319.
    JscompClientConstructUnsupportedInJs = 319,
    /// Catalog entry 320.
    SideGetenvNotCompileTimeString = 320,
    /// Catalog entry 321.
    HintSideGetenvNotCompileTimeString = 321,
    /// Catalog entry 322.
    UrpLibraryProjectParseFailed = 322,
    /// Catalog entry 323.
    UrpUnrecognizedDirective = 323,
    /// Catalog entry 324.
    CompilerInternalLockPoisoned = 324,
    /// Catalog entry 325.
    CoreEspecializeMissingSpecializationMetadata = 325,
    /// Catalog entry 326.
    CoreLocalReductionStaticCaseArmMissing = 326,
    /// Catalog entry 327.
    CliManifestMissingOrchestrator = 327,
    /// Catalog entry 328.
    CliManifestMissingFmt = 328,
    /// Catalog entry 329.
    CliManifestEntryRequired = 329,
    /// Catalog entry 330.
    CliUrTomlReadFailed = 330,
    /// Catalog entry 331.
    CliUrTomlParseFailed = 331,
    /// Catalog entry 332.
    CliUrTomlMissingInstall = 332,
    /// Catalog entry 333.
    CliManifestDatabaseEngineInvalid = 333,
    /// Catalog entry 334.
    CliPeerBinaryNotFound = 334,
    /// Catalog entry 335.
    CliScssCompilationFailed = 335,
    /// Catalog entry 336.
    CliOrchestratorScssCompiling = 336,
    /// Catalog entry 337.
    CliOrchestratorBuildingApp = 337,
    /// Catalog entry 338.
    CliOrchestratorTypeCheckingLib = 338,
    /// Catalog entry 339.
    CliOrchestratorUsageMoreHelp = 339,
    /// Catalog entry 340.
    CliDispatchMissingSubcommand = 340,
    /// Catalog entry 341.
    CliDispatchRunHelpHint = 341,
    /// Catalog entry 342.
    CliUsageHeading = 342,
    /// Catalog entry 343.
    CliOrchestratorUsageLines = 343,
    /// Catalog entry 344.
    CliUrCompileHelpExtra = 344,
    /// Catalog entry 345.
    CliUrFmtHelp = 345,
    /// Catalog entry 346.
    CliUrFmtNoSourceFilesFound = 346,
    /// Catalog entry 347.
    CliUrFmtProjectUrpNotFound = 347,
    /// Catalog entry 348.
    CliUrFmtUnknownFlag = 348,
    /// Catalog entry 349.
    CliUrFmtNotUrFile = 349,
    /// Catalog entry 350.
    CliUrFmtFileMissing = 350,
    /// Catalog entry 351.
    CliUrFmtReadFailed = 351,
    /// Catalog entry 352.
    CliUrFmtCheckWouldChange = 352,
    /// Catalog entry 353.
    CliUrFmtWriteFailed = 353,
    /// Catalog entry 354.
    CliUrFmtParseFailedHeader = 354,
    /// Catalog entry 355.
    CliInstallPackagePresent = 355,
    /// Catalog entry 356.
    CliInstallInProgress = 356,
    /// Catalog entry 357.
    CliInstallSucceeded = 357,
    /// Catalog entry 358.
    CliInstallUrpHint = 358,
    /// Catalog entry 359.
    CliInstallGitFailed = 359,
    /// Catalog entry 360.
    CliInstallUsage = 360,
    /// Catalog entry 361.
    CliDaemonStopped = 361,
    /// Catalog entry 362.
    CliDaemonNotImplemented = 362,
    /// Catalog entry 363.
    CliDaemonUsage = 363,
    /// Catalog entry 364.
    CliUrNewCreated = 364,
    /// Catalog entry 365.
    CliUrNewGitNote = 365,
    /// Catalog entry 366.
    CliUrNewBuildHint = 366,
    /// Catalog entry 367.
    CliUrNewUsageApp = 367,
    /// Catalog entry 368.
    CliUrNewUsageLib = 368,
    /// Catalog entry 369.
    CliDemoRequiresDirectory = 369,
    /// Catalog entry 370.
    CliNoProjectSeeHelp = 370,
    /// Catalog entry 371.
    CliInvalidLimitNumber = 371,
    /// Catalog entry 372.
    CliUnknownCompilerFlag = 372,
    /// Catalog entry 373.
    CliCompilerWorkerSpawnFailed = 373,
    /// Catalog entry 374.
    CliCompilerWorkerPanicked = 374,
    /// Catalog entry 375.
    CliCompilerPhaseTiming = 375,
    /// Catalog entry 376.
    CliDumpOutputUsage = 376,
    /// Catalog entry 377.
    CliDumpOutputChdirFailed = 377,
    /// Catalog entry 378.
    CliDumpOutputCompileFailed = 378,
    /// Catalog entry 379.
    CliTestParseHasErrors = 379,
    /// Catalog entry 380.
    CliTestParseDeclCount = 380,
    /// Catalog entry 381.
    CliTestParseFailed = 381,
    /// Catalog entry 382.
    CliTestParseTwoDecls = 382,
    /// Catalog entry 383.
    CliTestParseTwoDeclsFailed = 383,
    /// Catalog entry 384.
    CliTestPpContextOk = 384,
    /// Catalog entry 385.
    CliFileReadFailed = 385,
    /// Catalog entry 386.
    CliTomlParseAtPathFailed = 386,
    /// Catalog entry 387.
    CliPackageLanguageInvalid = 387,
    /// Catalog entry 388.
    CliBuildDatabaseEngineMismatch = 388,
    /// Catalog entry 389.
    CliProjectNameEmpty = 389,
    /// Catalog entry 390.
    CliProjectNameMustStartWithLetter = 390,
    /// Catalog entry 391.
    CliProjectNameInvalidCharacters = 391,
    /// Catalog entry 392.
    CliUrNewDirectoryExists = 392,
    /// Catalog entry 393.
    CliUrNewScaffoldIoFailed = 393,
    /// Catalog entry 394.
    CliDatabaseBackendCliRejected = 394,
    /// Catalog entry 395.
    CliCompileResourceLimitConfiguration = 395,
    /// Catalog entry 396.
    CliDemoModeFailed = 396,
    /// Catalog entry 397.
    CliLspRunFailed = 397,
    /// Catalog entry 398.
    CliLspProjectOpenFailed = 398,
    /// Catalog entry 399.
    CliLspWorkspaceChdirFailed = 399,
    /// Catalog entry 400.
    CliLspWorkspaceReadDirFailed = 400,
    /// Catalog entry 401.
    CliLspWorkspaceDirEntryFailed = 401,
    /// Catalog entry 402.
    CliLspWorkspaceNoUrProjectFile = 402,
    /// Catalog entry 403.
    CliLspWorkspaceUrpPathInternal = 403,
    /// Catalog entry 404.
    CliLspWorkspaceMultipleUrProjectFiles = 404,
    /// Catalog entry 405.
    CliLspProjectResolveFailed = 405,
    /// Catalog entry 406.
    CliCompileStoppedAfterDiagnostics = 406,
    /// Catalog entry 407.
    CliCCompilerRejectedGeneratedFile = 407,
    /// Catalog entry 408.
    CliLinkerCouldNotProduceExecutable = 408,
    /// Catalog entry 409.
    CliWriteGeneratedCFileFailed = 409,
    /// Catalog entry 410.
    CliToolBannerCompileStopped = 410,
    /// Catalog entry 411.
    CliToolBannerCBuild = 411,
    /// Catalog entry 412.
    CliToolBannerLink = 412,
    /// Catalog entry 413.
    CliCompileWriteSqlFileFailed = 413,
    /// Catalog entry 414.
    CliUrpDirectiveParseFailed = 414,
    /// Catalog entry 415.
    CliUrpInvalidUnsignedIntegerDirective = 415,
    /// Catalog entry 416.
    CliSubprocessSpawnFailed = 416,
    /// Catalog entry 417.
    CliSubprocessPollFailed = 417,
    /// Catalog entry 418.
    CliSubprocessRunFailed = 418,
    /// Catalog entry 419.
    CliCompilerCcLinkTestDeadlineExceeded = 419,
    /// Catalog entry 420.
    CliUrpFfiExpectedModuleDotFunc = 420,
    /// Catalog entry 421.
    CliUrpFfiMapExpectedModuleFuncEquals = 421,
    /// Catalog entry 422.
    CliUrpUnknownRewritePathKind = 422,
    /// Catalog entry 423.
    CliUrpOnErrorNeedsQualifiedName = 423,
    /// Catalog entry 424.
    CliUrpRewriteBadSyntax = 424,
    /// Catalog entry 425.
    CliUrpAllowBadSyntax = 425,
    /// Catalog entry 426.
    CliUrpDenyBadSyntax = 426,
    /// Catalog entry 427.
    CliUrpUnknownFilterKind = 427,
    /// Catalog entry 428.
    CliUrpLibraryNotFound = 428,
    /// Catalog entry 429.
    CliDebuggerGdbStdoutClosed = 429,
    /// Catalog entry 430.
    CliDebuggerGdbLineQueueMutexPoisoned = 430,
    /// Catalog entry 431.
    CliDebuggerGdbMiReported = 431,
    /// Catalog entry 432.
    CliDebuggerSpawnMiBackendFailed = 432,
    /// Catalog entry 433.
    CliDebuggerSetVariableNameNotSimpleCIdentifier = 433,
    /// Catalog entry 434.
    CliDebuggerDapStaleVariablesReference = 434,
    /// Catalog entry 435.
    CliDebuggerDapVarCreateFailed = 435,
    /// Catalog entry 436.
    CliDebuggerDapNotVariableContainer = 436,
    /// Catalog entry 437.
    CliDebuggerDapFieldNotFound = 437,
    /// Catalog entry 438.
    CliDebuggerDapNoLaunchBeforeConfigurationDone = 438,
    /// Catalog entry 439.
    CliDebuggerDapAttachFailed = 439,
    /// Catalog entry 440.
    CliDebuggerDapLoadSymbolsFailed = 440,
    /// Catalog entry 441.
    CliDebuggerDapRunInferiorFailed = 441,
    /// Catalog entry 442.
    CliDebuggerDapGdbSessionMissing = 442,
    /// Catalog entry 443.
    CliDebuggerDapRequestBeforeLaunch = 443,
    /// Catalog entry 444.
    CliDebuggerDapReadSourceFailed = 444,
    /// Catalog entry 445.
    CliDebuggerDapDisassembleNeedsMemoryReference = 445,
    /// Catalog entry 446.
    CliDebuggerDapSourceRequiresPathProperty = 446,
    /// Catalog entry 447.
    CliDebuggerDapAttachRequiresProcessId = 447,
    /// Catalog entry 448.
    CliDebuggerDapLaunchRequiresProgram = 448,
    /// Catalog entry 449.
    CliDebuggerDapExceptionNoSignalDetailsThisThread = 449,
    /// Catalog entry 450.
    CliDebuggerDapExceptionNoInformation = 450,
    /// Catalog entry 451.
    CliDebuggerDapBreakpointPendingAfterConfigurationDone = 451,
    /// Catalog entry 452.
    CliDebuggerDapBreakpointGdbCouldNotSet = 452,
    /// Catalog entry 453.
    CliDebuggerDapStoppedSignalLabel = 453,
    /// Catalog entry 454.
    CliDebuggerDapExceptionDeliveredSignalDescription = 454,
    /// Catalog entry 455.
    CliDebuggerDapThreadDisplayName = 455,
    /// Catalog entry 456.
    CliDebuggerDapScopeLocalsName = 456,
    /// Catalog entry 457.
    CliDebuggerDapFilterLabelFatalSignals = 457,
    /// Catalog entry 458.
    CliDebuggerDapFilterLabelAllSignals = 458,
    /// Catalog entry 459.
    CliDebuggerDapFilterLabelCppThrow = 459,
    /// Catalog entry 460.
    CliDebuggerUnknownFlag = 460,
    /// Catalog entry 461.
    CliDebuggerMissingMode = 461,
    /// Catalog entry 462.
    CliDebuggerCliDapStdioFailed = 462,
    /// Catalog entry 463.
    CliDebuggerCliTtyRequiresProgramPath = 463,
    /// Catalog entry 464.
    CliDebuggerRunFailed = 464,
    /// Catalog entry 465.
    CliDebuggerGdbSpawnFailed = 465,
    /// Catalog entry 466.
    CliDebuggerGdbExecFailed = 466,
    /// Catalog entry 467.
    CliDebuggerGdbExitedNonZero = 467,
    /// Catalog entry 468.
    CliDebuggerUsageBody = 468,
    /// Catalog entry 469.
    CliDevPreprocessWindowFailed = 469,
    /// Catalog entry 470.
    CliPhaseIncompleteNoOutput = 470,
    /// Catalog entry 471.
    CliDebuggerGdbMiDriverLoopExhausted = 471,
    /// Catalog entry 472.
    CliDebuggerDapStdioLoopExhausted = 472,
    /// Catalog entry 473.
    CliBootRootNotFound = 473,
    /// Catalog entry 474.
    CliBootRootMissingBasis = 474,
    /// Catalog entry 475.
    CompilerInternalBug = 475,
    /// Catalog entry 476.
    CliDatabaseBackendUrpRejected = 476,
    /// Catalog entry 477.
    CliCompilationJobCorrelationLine = 477,
    /// Catalog entry 478.
    CliCompilerTracingPhaseCompleteDebug = 478,
    /// Catalog entry 479.
    CliCompilerTracingJobCompileStart = 479,
    /// Catalog entry 480.
    CliCompilerTracingJobCompileFinished = 480,
    /// Catalog entry 481.
    CliCompilerTracingPipelineOutputsStart = 481,
    /// Catalog entry 482.
    CliCompilerTracingPipelineOutputsFinished = 482,
    /// Catalog entry 483.
    CliCompilerTracingElaborateProjectStart = 483,
    /// Catalog entry 484.
    CliCompilerTracingCCompileObjectStep = 484,
    /// Catalog entry 485.
    CliCompilerTracingCLinkExeStep = 485,
}
