//! Auto-generated by scripts/gen_diagnostic_catalog.py — do not hand-edit.

#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DiagnosticId {
    /// Catalog entry 1.
    EmptyPlain = 1,
    /// Catalog entry 2.
    UnboundKindVariable = 2,
    /// Catalog entry 3.
    HintUnboundKindVariable = 3,
    /// Catalog entry 4.
    WildcardDisallowedInSignature = 4,
    /// Catalog entry 5.
    HintWildcardDisallowedInSignature = 5,
    /// Catalog entry 6.
    UnboundConstructorVariable = 6,
    /// Catalog entry 7.
    HintUnboundConstructorVariable = 7,
    /// Catalog entry 8.
    UnboundDatatypeName = 8,
    /// Catalog entry 9.
    HintUnboundDatatypeName = 9,
    /// Catalog entry 10.
    UnboundStructureReference = 10,
    /// Catalog entry 11.
    HintUnboundStructureReference = 11,
    /// Catalog entry 12.
    ConstructorWrongKind = 12,
    /// Catalog entry 13.
    HintConstructorWrongKind = 13,
    /// Catalog entry 14.
    DuplicateRecordFieldName = 14,
    /// Catalog entry 15.
    HintDuplicateRecordFieldName = 15,
    /// Catalog entry 16.
    ProjectionIndexOutOfBounds = 16,
    /// Catalog entry 17.
    HintProjectionIndexOutOfBounds = 17,
    /// Catalog entry 18.
    ProjectionKindMismatch = 18,
    /// Catalog entry 19.
    HintProjectionKindMismatch = 19,
    /// Catalog entry 20.
    ConstructorWildcardDisallowedInSignatureConstructor = 20,
    /// Catalog entry 21.
    HintConstructorWildcardDisallowedInSignatureConstructor = 21,
    /// Catalog entry 22.
    KindOccursCheckFailed = 22,
    /// Catalog entry 23.
    IncompatibleKinds = 23,
    /// Catalog entry 24.
    ScopePreventsKindUnification = 24,
    /// Catalog entry 25.
    NestedKindUnificationFailure = 25,
    /// Catalog entry 26.
    ConstructorOccursCheckFailed = 26,
    /// Catalog entry 27.
    IncompatibleConstructorsUnif = 27,
    /// Catalog entry 28.
    TypeFunctionExplicitnessMismatch = 28,
    /// Catalog entry 29.
    UnexpectedKindForKindofQuery = 29,
    /// Catalog entry 30.
    RecordConstructorUnificationFailure = 30,
    /// Catalog entry 31.
    SuspendedLiftingClash = 31,
    /// Catalog entry 32.
    SubstitutionBlockedByDeepUnification = 32,
    /// Catalog entry 33.
    UnificationLiftingTooDeep = 33,
    /// Catalog entry 34.
    ScopePreventsConstructorUnification = 34,
    /// Catalog entry 35.
    UnboundExpressionVariable = 35,
    /// Catalog entry 36.
    HintUnboundExpressionVariable = 36,
    /// Catalog entry 37.
    UnboundStructureInExpression = 37,
    /// Catalog entry 38.
    HintUnboundStructureInExpression = 38,
    /// Catalog entry 39.
    ExpressionUnificationFailure = 39,
    /// Catalog entry 40.
    HintExpressionUnificationFailure = 40,
    /// Catalog entry 41.
    UnificationVariableObstructsOperation = 41,
    /// Catalog entry 42.
    HintUnificationVariableObstructs = 42,
    /// Catalog entry 43.
    ExpressionWrongForm = 43,
    /// Catalog entry 44.
    HintExpressionWrongForm = 44,
    /// Catalog entry 45.
    IncompatibleConstructorsExpression = 45,
    /// Catalog entry 46.
    HintIncompatibleConstructorsExpression = 46,
    /// Catalog entry 47.
    DuplicatePatternVariable = 47,
    /// Catalog entry 48.
    HintDuplicatePatternVariable = 48,
    /// Catalog entry 49.
    PatternUnificationFailure = 49,
    /// Catalog entry 50.
    HintPatternUnificationFailure = 50,
    /// Catalog entry 51.
    UnboundQualifiedConstructor = 51,
    /// Catalog entry 52.
    HintUnboundQualifiedConstructor = 52,
    /// Catalog entry 53.
    PatternConstructorGivenArgumentButExpectsNone = 53,
    /// Catalog entry 54.
    HintPatternConstructorGivenArgumentButExpectsNone = 54,
    /// Catalog entry 55.
    PatternConstructorExpectsArgumentButNoneGiven = 55,
    /// Catalog entry 56.
    HintPatternConstructorExpectsArgumentButNoneGiven = 56,
    /// Catalog entry 57.
    InexhaustiveCaseAnalysis = 57,
    /// Catalog entry 58.
    DuplicatePatternRecordField = 58,
    /// Catalog entry 59.
    HintDuplicatePatternRecordField = 59,
    /// Catalog entry 60.
    UnresolvableTypeClassInstance = 60,
    /// Catalog entry 61.
    TypeClassWildcardOutOfContext = 61,
    /// Catalog entry 62.
    IllegalRecursiveValueBinding = 62,
    /// Catalog entry 63.
    HintIllegalRecursiveValueBinding = 63,
    /// Catalog entry 64.
    KindUnifiersRemainUndetermined = 64,
    /// Catalog entry 65.
    HintKindUnifiersRemainUndetermined = 65,
    /// Catalog entry 66.
    ConstructorUnifiersRemainUndetermined = 66,
    /// Catalog entry 67.
    HintConstructorUnifiersRemainUndetermined = 67,
    /// Catalog entry 68.
    NonStrictlyPositiveDeclaration = 68,
    /// Catalog entry 69.
    HintNonStrictlyPositiveDeclaration = 69,
    /// Catalog entry 70.
    TypeHoleFoundInternal = 70,
    /// Catalog entry 71.
    UnboundSignatureName = 71,
    /// Catalog entry 72.
    HintUnboundSignatureName = 72,
    /// Catalog entry 73.
    UnmatchedSignatureItem = 73,
    /// Catalog entry 74.
    HintUnmatchedSignatureItem = 74,
    /// Catalog entry 75.
    SignatureItemKindUnificationFailed = 75,
    /// Catalog entry 76.
    SignatureItemConstructorUnificationFailed = 76,
    /// Catalog entry 77.
    SignatureItemDatatypeSpecificationsMismatch = 77,
    /// Catalog entry 78.
    IncompatibleSignatureShapes = 78,
    /// Catalog entry 79.
    WhereClauseFieldUnavailable = 79,
    /// Catalog entry 80.
    HintWhereClauseFieldUnavailable = 80,
    /// Catalog entry 81.
    WhereClauseKindMismatch = 81,
    /// Catalog entry 82.
    SignatureNotValidForInclude = 82,
    /// Catalog entry 83.
    HintSignatureNotValidForInclude = 83,
    /// Catalog entry 84.
    DuplicateConstructorNameInSignature = 84,
    /// Catalog entry 85.
    HintDuplicateConstructorNameInSignature = 85,
    /// Catalog entry 86.
    DuplicateValueNameInSignature = 86,
    /// Catalog entry 87.
    HintDuplicateValueNameInSignature = 87,
    /// Catalog entry 88.
    DuplicateNestedSignatureNameInSignature = 88,
    /// Catalog entry 89.
    HintDuplicateNestedSignatureNameInSignature = 89,
    /// Catalog entry 90.
    DuplicateStructureNameInSignature = 90,
    /// Catalog entry 91.
    HintDuplicateStructureNameInSignature = 91,
    /// Catalog entry 92.
    SignatureNotValidForOpenConstraints = 92,
    /// Catalog entry 93.
    HintSignatureNotValidForOpenConstraints = 93,
    /// Catalog entry 94.
    UnboundStructureVariable = 94,
    /// Catalog entry 95.
    HintUnboundStructureVariable = 95,
    /// Catalog entry 96.
    AppliedNonFunctor = 96,
    /// Catalog entry 97.
    HintAppliedNonFunctor = 97,
    /// Catalog entry 98.
    FunctorRebindingAttempt = 98,
    /// Catalog entry 99.
    HintFunctorRebindingAttempt = 99,
    /// Catalog entry 100.
    StructureNotOpenable = 100,
    /// Catalog entry 101.
    HintStructureNotOpenable = 101,
    /// Catalog entry 102.
    ValTypeKindIsNotType = 102,
    /// Catalog entry 103.
    DuplicateDatatypeConstructorNameInGroup = 103,
    /// Catalog entry 104.
    HintDuplicateDatatypeConstructorNameInGroup = 104,
    /// Catalog entry 105.
    ImportingNonDatatypeAsDatatype = 105,
    /// Catalog entry 106.
    HintImportingNonDatatypeAsDatatype = 106,
    /// Catalog entry 107.
    ElabKindMismatch = 107,
    /// Catalog entry 108.
    ElabUnboundKindVariableTemplate = 108,
    /// Catalog entry 109.
    ElabConstructorRecursionDepth = 109,
    /// Catalog entry 110.
    ElabConstructorAppNonArrow = 110,
    /// Catalog entry 111.
    ElabTupleProjectionOutOfBounds = 111,
    /// Catalog entry 112.
    ElabTupleProjectionNonTuple = 112,
    /// Catalog entry 113.
    ElabUnboundTypeConstructor = 113,
    /// Catalog entry 114.
    ElabUnboundModuleFirst = 114,
    /// Catalog entry 115.
    ElabModuleNonConstSignature = 115,
    /// Catalog entry 116.
    ElabSubModuleNonConstSignature = 116,
    /// Catalog entry 117.
    ElabNotAStructure = 117,
    /// Catalog entry 118.
    ElabUnboundModule = 118,
    /// Catalog entry 119.
    ElabUnboundRelConstructor = 119,
    /// Catalog entry 120.
    ElabUnboundNamedConstructor = 120,
    /// Catalog entry 121.
    ElabApplicationNonArrowKind = 121,
    /// Catalog entry 122.
    ElabKAppNonKFun = 122,
    /// Catalog entry 123.
    ElabTypeMismatch = 123,
    /// Catalog entry 124.
    ElabConstructorExpectsArgument = 124,
    /// Catalog entry 125.
    ElabConstructorDoesNotTakeArgument = 125,
    /// Catalog entry 126.
    ElabUnboundConstructor = 126,
    /// Catalog entry 127.
    ElabExpressionRecursionDepth = 127,
    /// Catalog entry 128.
    ElabApplicationNonFunction = 128,
    /// Catalog entry 129.
    ElabConstructorAppNonTcFun = 129,
    /// Catalog entry 130.
    ElabUnboundVariable = 130,
    /// Catalog entry 131.
    ElabImplicitArgIterationLimit = 131,
    /// Catalog entry 132.
    ElabUnboundDatatype = 132,
    /// Catalog entry 133.
    ElabUnboundSignature = 133,
    /// Catalog entry 134.
    ElabUnboundModuleForSignature = 134,
    /// Catalog entry 135.
    ElabSignatureMismatch = 135,
    /// Catalog entry 136.
    ElabSignatureMissingValue = 136,
    /// Catalog entry 137.
    ElabKindMismatchForSignatureValue = 137,
    /// Catalog entry 138.
    ElabWrongConstructorKindFor = 138,
    /// Catalog entry 139.
    ElabSignatureMissingType = 139,
    /// Catalog entry 140.
    ElabWrongTypeForSignature = 140,
    /// Catalog entry 141.
    ElabSignatureMissingStructure = 141,
    /// Catalog entry 142.
    ElabCannotOpenNonConstModule = 142,
    /// Catalog entry 143.
    ElabUnboundStructure = 143,
    /// Catalog entry 144.
    ElabNoStructureInModule = 144,
    /// Catalog entry 145.
    ElabApplicationNonFunctorStructure = 145,
    /// Catalog entry 146.
    ElabUnresolvedDisjointness = 146,
    /// Catalog entry 147.
    ElabUnresolvedTypeclass = 147,
    /// Catalog entry 148.
    CouldNotReadBasisUrs = 148,
    /// Catalog entry 149.
    CouldNotReadTopUrs = 149,
    /// Catalog entry 150.
    CouldNotReadTopUr = 150,
    /// Catalog entry 151.
    CouldNotReadFfiUrs = 151,
    /// Catalog entry 152.
    CouldNotReadSourceUr = 152,
    /// Catalog entry 153.
    CouldNotReadSignatureUrs = 153,
    /// Catalog entry 154.
    ParserNotLinkedUr = 154,
    /// Catalog entry 155.
    ParserNotLinkedUrs = 155,
    /// Catalog entry 156.
    ParseUrSyntaxFailed = 156,
    /// Catalog entry 157.
    HintParseUrSyntax = 157,
    /// Catalog entry 158.
    ParseUrXmlHeuristicNote = 158,
    /// Catalog entry 159.
    ParseUrsSyntaxFailed = 159,
    /// Catalog entry 160.
    HintParseUrsSyntax = 160,
    /// Catalog entry 161.
    ExplifyKindErrorPlaceholder = 161,
    /// Catalog entry 162.
    HintExplifyKindErrorPlaceholder = 162,
    /// Catalog entry 163.
    ExplifyKindMetavarUnknown = 163,
    /// Catalog entry 164.
    HintExplifyKindMetavarUnknown = 164,
    /// Catalog entry 165.
    ExplifyTupleKindMetavarUnknown = 165,
    /// Catalog entry 166.
    HintExplifyTupleKindMetavarUnknown = 166,
    /// Catalog entry 167.
    ExplifyUnexpectedConstructorError = 167,
    /// Catalog entry 168.
    ExplifyConstructorMetavarUnknown = 168,
    /// Catalog entry 169.
    HintExplifyConstructorMetavarUnknown = 169,
    /// Catalog entry 170.
    ExplifyUnexpectedExpressionError = 170,
    /// Catalog entry 171.
    ExplifyExpressionUnificationUnknown = 171,
    /// Catalog entry 172.
    ExplifyTypedHoleRemains = 172,
    /// Catalog entry 173.
    ExplifyLocalValRecShouldBeLifted = 173,
    /// Catalog entry 174.
    ExplifySignatureErrorPlaceholder = 174,
    /// Catalog entry 175.
    HintExplifySignatureErrorPlaceholder = 175,
    /// Catalog entry 176.
    ExplifyStructureErrorPlaceholder = 176,
    /// Catalog entry 177.
    HintExplifyStructureErrorPlaceholder = 177,
    /// Catalog entry 178.
    UnnestRemapFailedInternal = 178,
    /// Catalog entry 179.
    InformationFlowPolicyViolation = 179,
    /// Catalog entry 180.
    HintInformationFlowPolicyViolation = 180,
    /// Catalog entry 181.
    DatabasePolicyMayViolate = 181,
    /// Catalog entry 182.
    HintDatabasePolicyMayViolate = 182,
    /// Catalog entry 183.
    SerializationExcludedTypes = 183,
    /// Catalog entry 184.
    HintSerializationExcludedTypes = 184,
    /// Catalog entry 185.
    ExportNamesUndefinedValue = 185,
    /// Catalog entry 186.
    HintExportNamesUndefinedValue = 186,
    /// Catalog entry 187.
    ExportedHandlerUnsafeTypes = 187,
    /// Catalog entry 188.
    HintExportedHandlerUnsafeTypes = 188,
    /// Catalog entry 189.
    CookieStoresUnmarshallableTypes = 189,
    /// Catalog entry 190.
    HintCookieStoresUnmarshallableTypes = 190,
    /// Catalog entry 191.
    TerminationValRecNotProved = 191,
    /// Catalog entry 192.
    HintTerminationValRecNotProved = 192,
    /// Catalog entry 193.
    RpcInternalMissingTranslation = 193,
    /// Catalog entry 194.
    RpcCodeNotNamedFunction = 194,
    /// Catalog entry 195.
    RpcUndetectedTransactionFunction = 195,
    /// Catalog entry 196.
    ExportDuplicateUrlPrefix = 196,
    /// Catalog entry 197.
    ExportFunctionMultipleModes = 197,
    /// Catalog entry 198.
    ExportFunctionMultipleModesShort = 198,
    /// Catalog entry 199.
    ExportInvalidTagExpression = 199,
    /// Catalog entry 200.
    IoSomethingWrongReadingWriting = 200,
    /// Catalog entry 201.
    LspUnusedValueNeverUsedFromEntry = 201,
    /// Catalog entry 202.
    HintLspUnusedValueNeverUsedFromEntry = 202,
    /// Catalog entry 203.
    LspUnusedValRecNotReachable = 203,
    /// Catalog entry 204.
    HintLspUnusedValRecNotReachable = 204,
    /// Catalog entry 205.
    CjrizeAnonymousFunctionRemains = 205,
    /// Catalog entry 206.
    CjrizeNestedClosureRemains = 206,
    /// Catalog entry 207.
    CjrizeJavaScriptStillPresent = 207,
    /// Catalog entry 208.
    HintCjrizeJavaScriptStillPresent = 208,
    /// Catalog entry 209.
    CjrizeSignalReturnInvalidServer = 209,
    /// Catalog entry 210.
    HintCjrizeSignalReturnInvalidServer = 210,
    /// Catalog entry 211.
    CjrizeSignalBindInvalidServer = 211,
    /// Catalog entry 212.
    HintCjrizeSignalBindInvalidServer = 212,
    /// Catalog entry 213.
    CjrizeSignalSourceInvalidServer = 213,
    /// Catalog entry 214.
    HintCjrizeSignalSourceInvalidServer = 214,
    /// Catalog entry 215.
    CjrizeRpcStillOnServer = 215,
    /// Catalog entry 216.
    HintCjrizeRpcStillOnServer = 216,
    /// Catalog entry 217.
    CjrizeChannelRecvUnsupportedServer = 217,
    /// Catalog entry 218.
    HintCjrizeChannelRecvUnsupportedServer = 218,
    /// Catalog entry 219.
    CjrizeSleepInvalidServer = 219,
    /// Catalog entry 220.
    HintCjrizeSleepInvalidServer = 220,
    /// Catalog entry 221.
    CjrizeSpawnInvalidServer = 221,
    /// Catalog entry 222.
    HintCjrizeSpawnInvalidServer = 222,
    /// Catalog entry 223.
    CjrizeTableConstraintNotSimpleString = 223,
    /// Catalog entry 224.
    HintCjrizeTableConstraintNotSimpleString = 224,
    /// Catalog entry 225.
    MutationTestingBadPlaceholder = 225,
    /// Catalog entry 226.
    CorifyInternalCannotDeclareTypeInFfi = 226,
    /// Catalog entry 227.
    CorifyInternalCannotBindValueInFfi = 227,
    /// Catalog entry 228.
    CorifyInternalCannotBindDataConstructorValueInFfi = 228,
    /// Catalog entry 229.
    CorifyInternalCannotBindDataConstructorInFfi = 229,
    /// Catalog entry 230.
    CorifyStructureNestingStackUnderflow = 230,
    /// Catalog entry 231.
    CorifyInternalCannotBindNestedStructureInFfi = 231,
    /// Catalog entry 232.
    CorifyInternalCannotBindFunctorInFfi = 232,
    /// Catalog entry 233.
    CorifyUnknownStructureIdInPath = 233,
    /// Catalog entry 234.
    CorifyUnknownSubmoduleInPath = 234,
    /// Catalog entry 235.
    CorifyNotValueOrConstructorAtPath = 235,
    /// Catalog entry 236.
    CorifyUnknownImportedDataConstructor = 236,
    /// Catalog entry 237.
    CorifyInternalValBindingExpectedNamed = 237,
    /// Catalog entry 238.
    CorifyNotSubmoduleOrFunctor = 238,
    /// Catalog entry 239.
    CorifyUnknownStructureVariableId = 239,
    /// Catalog entry 240.
    CorifyNonConstFfiSignature = 240,
    /// Catalog entry 241.
    CorifyStructureTooFancyToExport = 241,
    /// Catalog entry 242.
    CorifyBasisMissingForExport = 242,
    /// Catalog entry 243.
    CorifyExportDidNotCorifyToGlobalName = 243,
    /// Catalog entry 244.
    CorifyNonConstSignatureForExport = 244,
    /// Catalog entry 245.
    CorifyWrongOnErrorIdentifier = 245,
    /// Catalog entry 246.
    CorifyFfiNotAtModuleTopLevel = 246,
    /// Catalog entry 247.
    CorifyUnknownStructureId = 247,
    /// Catalog entry 248.
    CorifyUnknownSubmoduleInProjection = 248,
    /// Catalog entry 249.
    CorifyNestedFunctorInApplicationUnsupported = 249,
    /// Catalog entry 250.
    CorifyFunctorApplicationUnsupportedForm = 250,
    /// Catalog entry 251.
    InvalidHtml5DataAttribute = 251,
    /// Catalog entry 252.
    InvalidUrlPassedToBless = 252,
    /// Catalog entry 253.
    InvalidStringPassedToBlessMime = 253,
    /// Catalog entry 254.
    InvalidStringPassedToAtom = 254,
    /// Catalog entry 255.
    InvalidUrlPassedToCssUrl = 255,
    /// Catalog entry 256.
    InvalidStringPassedToProperty = 256,
    /// Catalog entry 257.
    InvalidStringPassedToBlessRequestHeader = 257,
    /// Catalog entry 258.
    InvalidStringPassedToBlessResponseHeader = 258,
    /// Catalog entry 259.
    InvalidStringPassedToBlessEnvVar = 259,
    /// Catalog entry 260.
    InvalidStringPassedToBlessMeta = 260,
    /// Catalog entry 261.
    PathTwoConstraintsSameGeneratedPath = 261,
    /// Catalog entry 262.
    HintPathTwoConstraintsSameGeneratedPath = 262,
    /// Catalog entry 263.
    PathTwoExportsSameUrl = 263,
    /// Catalog entry 264.
    HintPathTwoExportsSameUrl = 264,
    /// Catalog entry 265.
    PathTableOrSequenceDeclaredTwice = 265,
    /// Catalog entry 266.
    HintPathTableOrSequenceDeclaredTwice = 266,
    /// Catalog entry 267.
    PathPrimaryKeyMetadataCollides = 267,
    /// Catalog entry 268.
    HintPathPrimaryKeyMetadataCollides = 268,
    /// Catalog entry 269.
    PathTwoCookiesSharePath = 269,
    /// Catalog entry 270.
    HintPathTwoCookiesSharePath = 270,
    /// Catalog entry 271.
    PathTwoStylesSamePath = 271,
    /// Catalog entry 272.
    HintPathTwoStylesSamePath = 272,
    /// Catalog entry 273.
    ScriptPushProtocolNotPersistent = 273,
    /// Catalog entry 274.
    HintScriptPushProtocolNotPersistent = 274,
    /// Catalog entry 275.
    SideServerCallsClientOnlyFfi = 275,
    /// Catalog entry 276.
    HintSideServerCallsClientOnlyFfi = 276,
    /// Catalog entry 277.
    SqlTablePrimaryKeyNotKnownString = 277,
    /// Catalog entry 278.
    HintSqlTablePrimaryKeyNotKnownString = 278,
    /// Catalog entry 279.
    SqlViewNotPlainString = 279,
    /// Catalog entry 280.
    HintSqlViewNotPlainStringStrcat = 280,
    /// Catalog entry 281.
    HintSqlViewNotPlainStringLiteral = 281,
    /// Catalog entry 282.
    CjrizeFunctionNotExplicitAtCodegen = 282,
    /// Catalog entry 283.
    CjrizeTaskKindNotFullyDetermined = 283,
    /// Catalog entry 284.
    CjrizeInitializerNotFullyDetermined = 284,
    /// Catalog entry 285.
    CorifyUnknownTypeNameInModulePath = 285,
    /// Catalog entry 286.
    CorifyUnknownPatternConstructorId = 286,
    /// Catalog entry 287.
    CorifyUnknownDataConstructorInModulePath = 287,
}
