//! Auto-generated by scripts/gen_diagnostic_catalog.py — do not hand-edit.

#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DiagnosticId {
    /// Catalog entry 1.
    EmptyPlain = 1,
    /// Catalog entry 2.
    UnboundKindVariable = 2,
    /// Catalog entry 3.
    HintUnboundKindVariable = 3,
    /// Catalog entry 4.
    WildcardDisallowedInSignature = 4,
    /// Catalog entry 5.
    HintWildcardDisallowedInSignature = 5,
    /// Catalog entry 6.
    UnboundConstructorVariable = 6,
    /// Catalog entry 7.
    HintUnboundConstructorVariable = 7,
    /// Catalog entry 8.
    UnboundDatatypeName = 8,
    /// Catalog entry 9.
    HintUnboundDatatypeName = 9,
    /// Catalog entry 10.
    UnboundStructureReference = 10,
    /// Catalog entry 11.
    HintUnboundStructureReference = 11,
    /// Catalog entry 12.
    ConstructorWrongKind = 12,
    /// Catalog entry 13.
    HintConstructorWrongKind = 13,
    /// Catalog entry 14.
    DuplicateRecordFieldName = 14,
    /// Catalog entry 15.
    HintDuplicateRecordFieldName = 15,
    /// Catalog entry 16.
    ProjectionIndexOutOfBounds = 16,
    /// Catalog entry 17.
    HintProjectionIndexOutOfBounds = 17,
    /// Catalog entry 18.
    ProjectionKindMismatch = 18,
    /// Catalog entry 19.
    HintProjectionKindMismatch = 19,
    /// Catalog entry 20.
    ConstructorWildcardDisallowedInSignatureConstructor = 20,
    /// Catalog entry 21.
    HintConstructorWildcardDisallowedInSignatureConstructor = 21,
    /// Catalog entry 22.
    KindOccursCheckFailed = 22,
    /// Catalog entry 23.
    IncompatibleKinds = 23,
    /// Catalog entry 24.
    ScopePreventsKindUnification = 24,
    /// Catalog entry 25.
    NestedKindUnificationFailure = 25,
    /// Catalog entry 26.
    ConstructorOccursCheckFailed = 26,
    /// Catalog entry 27.
    IncompatibleConstructorsUnif = 27,
    /// Catalog entry 28.
    TypeFunctionExplicitnessMismatch = 28,
    /// Catalog entry 29.
    UnexpectedKindForKindofQuery = 29,
    /// Catalog entry 30.
    RecordConstructorUnificationFailure = 30,
    /// Catalog entry 31.
    SuspendedLiftingClash = 31,
    /// Catalog entry 32.
    SubstitutionBlockedByDeepUnification = 32,
    /// Catalog entry 33.
    UnificationLiftingTooDeep = 33,
    /// Catalog entry 34.
    ScopePreventsConstructorUnification = 34,
    /// Catalog entry 35.
    UnboundExpressionVariable = 35,
    /// Catalog entry 36.
    HintUnboundExpressionVariable = 36,
    /// Catalog entry 37.
    UnboundStructureInExpression = 37,
    /// Catalog entry 38.
    HintUnboundStructureInExpression = 38,
    /// Catalog entry 39.
    ExpressionUnificationFailure = 39,
    /// Catalog entry 40.
    HintExpressionUnificationFailure = 40,
    /// Catalog entry 41.
    UnificationVariableObstructsOperation = 41,
    /// Catalog entry 42.
    HintUnificationVariableObstructs = 42,
    /// Catalog entry 43.
    ExpressionWrongForm = 43,
    /// Catalog entry 44.
    HintExpressionWrongForm = 44,
    /// Catalog entry 45.
    IncompatibleConstructorsExpression = 45,
    /// Catalog entry 46.
    HintIncompatibleConstructorsExpression = 46,
    /// Catalog entry 47.
    DuplicatePatternVariable = 47,
    /// Catalog entry 48.
    HintDuplicatePatternVariable = 48,
    /// Catalog entry 49.
    PatternUnificationFailure = 49,
    /// Catalog entry 50.
    HintPatternUnificationFailure = 50,
    /// Catalog entry 51.
    UnboundQualifiedConstructor = 51,
    /// Catalog entry 52.
    HintUnboundQualifiedConstructor = 52,
    /// Catalog entry 53.
    PatternConstructorGivenArgumentButExpectsNone = 53,
    /// Catalog entry 54.
    HintPatternConstructorGivenArgumentButExpectsNone = 54,
    /// Catalog entry 55.
    PatternConstructorExpectsArgumentButNoneGiven = 55,
    /// Catalog entry 56.
    HintPatternConstructorExpectsArgumentButNoneGiven = 56,
    /// Catalog entry 57.
    InexhaustiveCaseAnalysis = 57,
    /// Catalog entry 58.
    DuplicatePatternRecordField = 58,
    /// Catalog entry 59.
    HintDuplicatePatternRecordField = 59,
    /// Catalog entry 60.
    UnresolvableTypeClassInstance = 60,
    /// Catalog entry 61.
    TypeClassWildcardOutOfContext = 61,
    /// Catalog entry 62.
    IllegalRecursiveValueBinding = 62,
    /// Catalog entry 63.
    HintIllegalRecursiveValueBinding = 63,
    /// Catalog entry 64.
    KindUnifiersRemainUndetermined = 64,
    /// Catalog entry 65.
    HintKindUnifiersRemainUndetermined = 65,
    /// Catalog entry 66.
    ConstructorUnifiersRemainUndetermined = 66,
    /// Catalog entry 67.
    HintConstructorUnifiersRemainUndetermined = 67,
    /// Catalog entry 68.
    NonStrictlyPositiveDeclaration = 68,
    /// Catalog entry 69.
    HintNonStrictlyPositiveDeclaration = 69,
    /// Catalog entry 70.
    TypeHoleFoundInternal = 70,
    /// Catalog entry 71.
    UnboundSignatureName = 71,
    /// Catalog entry 72.
    HintUnboundSignatureName = 72,
    /// Catalog entry 73.
    UnmatchedSignatureItem = 73,
    /// Catalog entry 74.
    HintUnmatchedSignatureItem = 74,
    /// Catalog entry 75.
    SignatureItemKindUnificationFailed = 75,
    /// Catalog entry 76.
    SignatureItemConstructorUnificationFailed = 76,
    /// Catalog entry 77.
    SignatureItemDatatypeSpecificationsMismatch = 77,
    /// Catalog entry 78.
    IncompatibleSignatureShapes = 78,
    /// Catalog entry 79.
    WhereClauseFieldUnavailable = 79,
    /// Catalog entry 80.
    HintWhereClauseFieldUnavailable = 80,
    /// Catalog entry 81.
    WhereClauseKindMismatch = 81,
    /// Catalog entry 82.
    SignatureNotValidForInclude = 82,
    /// Catalog entry 83.
    HintSignatureNotValidForInclude = 83,
    /// Catalog entry 84.
    DuplicateConstructorNameInSignature = 84,
    /// Catalog entry 85.
    HintDuplicateConstructorNameInSignature = 85,
    /// Catalog entry 86.
    DuplicateValueNameInSignature = 86,
    /// Catalog entry 87.
    HintDuplicateValueNameInSignature = 87,
    /// Catalog entry 88.
    DuplicateNestedSignatureNameInSignature = 88,
    /// Catalog entry 89.
    HintDuplicateNestedSignatureNameInSignature = 89,
    /// Catalog entry 90.
    DuplicateStructureNameInSignature = 90,
    /// Catalog entry 91.
    HintDuplicateStructureNameInSignature = 91,
    /// Catalog entry 92.
    SignatureNotValidForOpenConstraints = 92,
    /// Catalog entry 93.
    HintSignatureNotValidForOpenConstraints = 93,
    /// Catalog entry 94.
    UnboundStructureVariable = 94,
    /// Catalog entry 95.
    HintUnboundStructureVariable = 95,
    /// Catalog entry 96.
    AppliedNonFunctor = 96,
    /// Catalog entry 97.
    HintAppliedNonFunctor = 97,
    /// Catalog entry 98.
    FunctorRebindingAttempt = 98,
    /// Catalog entry 99.
    HintFunctorRebindingAttempt = 99,
    /// Catalog entry 100.
    StructureNotOpenable = 100,
    /// Catalog entry 101.
    HintStructureNotOpenable = 101,
    /// Catalog entry 102.
    ValTypeKindIsNotType = 102,
    /// Catalog entry 103.
    DuplicateDatatypeConstructorNameInGroup = 103,
    /// Catalog entry 104.
    HintDuplicateDatatypeConstructorNameInGroup = 104,
    /// Catalog entry 105.
    ImportingNonDatatypeAsDatatype = 105,
    /// Catalog entry 106.
    HintImportingNonDatatypeAsDatatype = 106,
    /// Catalog entry 107.
    ElabKindMismatch = 107,
    /// Catalog entry 108.
    ElabUnboundKindVariableTemplate = 108,
    /// Catalog entry 109.
    ElabConstructorRecursionDepth = 109,
    /// Catalog entry 110.
    ElabConstructorAppNonArrow = 110,
    /// Catalog entry 111.
    ElabTupleProjectionOutOfBounds = 111,
    /// Catalog entry 112.
    ElabTupleProjectionNonTuple = 112,
    /// Catalog entry 113.
    ElabUnboundTypeConstructor = 113,
    /// Catalog entry 114.
    ElabUnboundModuleFirst = 114,
    /// Catalog entry 115.
    ElabModuleNonConstSignature = 115,
    /// Catalog entry 116.
    ElabSubModuleNonConstSignature = 116,
    /// Catalog entry 117.
    ElabNotAStructure = 117,
    /// Catalog entry 118.
    ElabUnboundModule = 118,
    /// Catalog entry 119.
    ElabUnboundRelConstructor = 119,
    /// Catalog entry 120.
    ElabUnboundNamedConstructor = 120,
    /// Catalog entry 121.
    ElabApplicationNonArrowKind = 121,
    /// Catalog entry 122.
    ElabKAppNonKFun = 122,
    /// Catalog entry 123.
    ElabTypeMismatch = 123,
    /// Catalog entry 124.
    ElabConstructorExpectsArgument = 124,
    /// Catalog entry 125.
    ElabConstructorDoesNotTakeArgument = 125,
    /// Catalog entry 126.
    ElabUnboundConstructor = 126,
    /// Catalog entry 127.
    ElabExpressionRecursionDepth = 127,
    /// Catalog entry 128.
    ElabApplicationNonFunction = 128,
    /// Catalog entry 129.
    ElabConstructorAppNonTcFun = 129,
    /// Catalog entry 130.
    ElabUnboundVariable = 130,
    /// Catalog entry 131.
    ElabImplicitArgIterationLimit = 131,
    /// Catalog entry 132.
    ElabUnboundDatatype = 132,
    /// Catalog entry 133.
    ElabUnboundSignature = 133,
    /// Catalog entry 134.
    ElabUnboundModuleForSignature = 134,
    /// Catalog entry 135.
    ElabSignatureMismatch = 135,
    /// Catalog entry 136.
    ElabSignatureMissingValue = 136,
    /// Catalog entry 137.
    ElabKindMismatchForSignatureValue = 137,
    /// Catalog entry 138.
    ElabWrongConstructorKindFor = 138,
    /// Catalog entry 139.
    ElabSignatureMissingType = 139,
    /// Catalog entry 140.
    ElabWrongTypeForSignature = 140,
    /// Catalog entry 141.
    ElabSignatureMissingStructure = 141,
    /// Catalog entry 142.
    ElabCannotOpenNonConstModule = 142,
    /// Catalog entry 143.
    ElabUnboundStructure = 143,
    /// Catalog entry 144.
    ElabNoStructureInModule = 144,
    /// Catalog entry 145.
    ElabApplicationNonFunctorStructure = 145,
    /// Catalog entry 146.
    ElabUnresolvedDisjointness = 146,
    /// Catalog entry 147.
    ElabUnresolvedTypeclass = 147,
    /// Catalog entry 148.
    CouldNotReadBasisUrs = 148,
    /// Catalog entry 149.
    CouldNotReadTopUrs = 149,
    /// Catalog entry 150.
    CouldNotReadTopUr = 150,
    /// Catalog entry 151.
    CouldNotReadFfiUrs = 151,
    /// Catalog entry 152.
    CouldNotReadSourceUr = 152,
    /// Catalog entry 153.
    CouldNotReadSignatureUrs = 153,
    /// Catalog entry 154.
    ParserNotLinkedUr = 154,
    /// Catalog entry 155.
    ParserNotLinkedUrs = 155,
    /// Catalog entry 156.
    ParseUrSyntaxFailed = 156,
    /// Catalog entry 157.
    HintParseUrSyntax = 157,
    /// Catalog entry 158.
    ParseUrXmlHeuristicNote = 158,
    /// Catalog entry 159.
    ParseUrsSyntaxFailed = 159,
    /// Catalog entry 160.
    HintParseUrsSyntax = 160,
    /// Catalog entry 161.
    ExplifyKindErrorPlaceholder = 161,
    /// Catalog entry 162.
    HintExplifyKindErrorPlaceholder = 162,
    /// Catalog entry 163.
    ExplifyKindMetavarUnknown = 163,
    /// Catalog entry 164.
    HintExplifyKindMetavarUnknown = 164,
    /// Catalog entry 165.
    ExplifyTupleKindMetavarUnknown = 165,
    /// Catalog entry 166.
    HintExplifyTupleKindMetavarUnknown = 166,
    /// Catalog entry 167.
    ExplifyUnexpectedConstructorError = 167,
    /// Catalog entry 168.
    ExplifyConstructorMetavarUnknown = 168,
    /// Catalog entry 169.
    HintExplifyConstructorMetavarUnknown = 169,
    /// Catalog entry 170.
    ExplifyUnexpectedExpressionError = 170,
    /// Catalog entry 171.
    ExplifyExpressionUnificationUnknown = 171,
    /// Catalog entry 172.
    ExplifyTypedHoleRemains = 172,
    /// Catalog entry 173.
    ExplifyLocalValRecShouldBeLifted = 173,
    /// Catalog entry 174.
    ExplifySignatureErrorPlaceholder = 174,
    /// Catalog entry 175.
    HintExplifySignatureErrorPlaceholder = 175,
    /// Catalog entry 176.
    ExplifyStructureErrorPlaceholder = 176,
    /// Catalog entry 177.
    HintExplifyStructureErrorPlaceholder = 177,
    /// Catalog entry 178.
    UnnestRemapFailedInternal = 178,
    /// Catalog entry 179.
    InformationFlowPolicyViolation = 179,
    /// Catalog entry 180.
    HintInformationFlowPolicyViolation = 180,
    /// Catalog entry 181.
    DatabasePolicyMayViolate = 181,
    /// Catalog entry 182.
    HintDatabasePolicyMayViolate = 182,
    /// Catalog entry 183.
    SerializationExcludedTypes = 183,
    /// Catalog entry 184.
    HintSerializationExcludedTypes = 184,
    /// Catalog entry 185.
    ExportNamesUndefinedValue = 185,
    /// Catalog entry 186.
    HintExportNamesUndefinedValue = 186,
    /// Catalog entry 187.
    ExportedHandlerUnsafeTypes = 187,
    /// Catalog entry 188.
    HintExportedHandlerUnsafeTypes = 188,
    /// Catalog entry 189.
    CookieStoresUnmarshallableTypes = 189,
    /// Catalog entry 190.
    HintCookieStoresUnmarshallableTypes = 190,
    /// Catalog entry 191.
    TerminationValRecNotProved = 191,
    /// Catalog entry 192.
    HintTerminationValRecNotProved = 192,
    /// Catalog entry 193.
    RpcInternalMissingTranslation = 193,
    /// Catalog entry 194.
    RpcCodeNotNamedFunction = 194,
    /// Catalog entry 195.
    RpcUndetectedTransactionFunction = 195,
    /// Catalog entry 196.
    ExportDuplicateUrlPrefix = 196,
    /// Catalog entry 197.
    ExportFunctionMultipleModes = 197,
    /// Catalog entry 198.
    ExportFunctionMultipleModesShort = 198,
    /// Catalog entry 199.
    ExportInvalidTagExpression = 199,
    /// Catalog entry 200.
    IoSomethingWrongReadingWriting = 200,
    /// Catalog entry 201.
    LspUnusedValueNeverUsedFromEntry = 201,
    /// Catalog entry 202.
    HintLspUnusedValueNeverUsedFromEntry = 202,
    /// Catalog entry 203.
    LspUnusedValRecNotReachable = 203,
    /// Catalog entry 204.
    HintLspUnusedValRecNotReachable = 204,
    /// Catalog entry 205.
    CjrizeAnonymousFunctionRemains = 205,
    /// Catalog entry 206.
    CjrizeNestedClosureRemains = 206,
    /// Catalog entry 207.
    CjrizeJavaScriptStillPresent = 207,
    /// Catalog entry 208.
    HintCjrizeJavaScriptStillPresent = 208,
    /// Catalog entry 209.
    CjrizeSignalReturnInvalidServer = 209,
    /// Catalog entry 210.
    HintCjrizeSignalReturnInvalidServer = 210,
    /// Catalog entry 211.
    CjrizeSignalBindInvalidServer = 211,
    /// Catalog entry 212.
    HintCjrizeSignalBindInvalidServer = 212,
    /// Catalog entry 213.
    CjrizeSignalSourceInvalidServer = 213,
    /// Catalog entry 214.
    HintCjrizeSignalSourceInvalidServer = 214,
    /// Catalog entry 215.
    CjrizeRpcStillOnServer = 215,
    /// Catalog entry 216.
    HintCjrizeRpcStillOnServer = 216,
    /// Catalog entry 217.
    CjrizeChannelRecvUnsupportedServer = 217,
    /// Catalog entry 218.
    HintCjrizeChannelRecvUnsupportedServer = 218,
    /// Catalog entry 219.
    CjrizeSleepInvalidServer = 219,
    /// Catalog entry 220.
    HintCjrizeSleepInvalidServer = 220,
    /// Catalog entry 221.
    CjrizeSpawnInvalidServer = 221,
    /// Catalog entry 222.
    HintCjrizeSpawnInvalidServer = 222,
    /// Catalog entry 223.
    CjrizeTableConstraintNotSimpleString = 223,
    /// Catalog entry 224.
    HintCjrizeTableConstraintNotSimpleString = 224,
    /// Catalog entry 225.
    MutationTestingBadPlaceholder = 225,
    /// Catalog entry 226.
    CorifyInternalCannotDeclareTypeInFfi = 226,
    /// Catalog entry 227.
    CorifyInternalCannotBindValueInFfi = 227,
    /// Catalog entry 228.
    CorifyInternalCannotBindDataConstructorValueInFfi = 228,
    /// Catalog entry 229.
    CorifyInternalCannotBindDataConstructorInFfi = 229,
    /// Catalog entry 230.
    CorifyStructureNestingStackUnderflow = 230,
    /// Catalog entry 231.
    CorifyInternalCannotBindNestedStructureInFfi = 231,
    /// Catalog entry 232.
    CorifyInternalCannotBindFunctorInFfi = 232,
    /// Catalog entry 233.
    CorifyUnknownStructureIdInPath = 233,
    /// Catalog entry 234.
    CorifyUnknownSubmoduleInPath = 234,
    /// Catalog entry 235.
    CorifyNotValueOrConstructorAtPath = 235,
    /// Catalog entry 236.
    CorifyUnknownImportedDataConstructor = 236,
    /// Catalog entry 237.
    CorifyInternalValBindingExpectedNamed = 237,
    /// Catalog entry 238.
    CorifyNotSubmoduleOrFunctor = 238,
    /// Catalog entry 239.
    CorifyUnknownStructureVariableId = 239,
    /// Catalog entry 240.
    CorifyNonConstFfiSignature = 240,
    /// Catalog entry 241.
    CorifyStructureTooFancyToExport = 241,
    /// Catalog entry 242.
    CorifyBasisMissingForExport = 242,
    /// Catalog entry 243.
    CorifyExportDidNotCorifyToGlobalName = 243,
    /// Catalog entry 244.
    CorifyNonConstSignatureForExport = 244,
    /// Catalog entry 245.
    CorifyWrongOnErrorIdentifier = 245,
    /// Catalog entry 246.
    CorifyFfiNotAtModuleTopLevel = 246,
    /// Catalog entry 247.
    CorifyUnknownStructureId = 247,
    /// Catalog entry 248.
    CorifyUnknownSubmoduleInProjection = 248,
    /// Catalog entry 249.
    CorifyNestedFunctorInApplicationUnsupported = 249,
    /// Catalog entry 250.
    CorifyFunctorApplicationUnsupportedForm = 250,
    /// Catalog entry 251.
    InvalidHtml5DataAttribute = 251,
    /// Catalog entry 252.
    InvalidUrlPassedToBless = 252,
    /// Catalog entry 253.
    InvalidStringPassedToBlessMime = 253,
    /// Catalog entry 254.
    InvalidStringPassedToAtom = 254,
    /// Catalog entry 255.
    InvalidUrlPassedToCssUrl = 255,
    /// Catalog entry 256.
    InvalidStringPassedToProperty = 256,
    /// Catalog entry 257.
    InvalidStringPassedToBlessRequestHeader = 257,
    /// Catalog entry 258.
    InvalidStringPassedToBlessResponseHeader = 258,
    /// Catalog entry 259.
    InvalidStringPassedToBlessEnvVar = 259,
    /// Catalog entry 260.
    InvalidStringPassedToBlessMeta = 260,
    /// Catalog entry 261.
    PathTwoConstraintsSameGeneratedPath = 261,
    /// Catalog entry 262.
    HintPathTwoConstraintsSameGeneratedPath = 262,
    /// Catalog entry 263.
    PathTwoExportsSameUrl = 263,
    /// Catalog entry 264.
    HintPathTwoExportsSameUrl = 264,
    /// Catalog entry 265.
    PathTableOrSequenceDeclaredTwice = 265,
    /// Catalog entry 266.
    HintPathTableOrSequenceDeclaredTwice = 266,
    /// Catalog entry 267.
    PathPrimaryKeyMetadataCollides = 267,
    /// Catalog entry 268.
    HintPathPrimaryKeyMetadataCollides = 268,
    /// Catalog entry 269.
    PathTwoCookiesSharePath = 269,
    /// Catalog entry 270.
    HintPathTwoCookiesSharePath = 270,
    /// Catalog entry 271.
    PathTwoStylesSamePath = 271,
    /// Catalog entry 272.
    HintPathTwoStylesSamePath = 272,
    /// Catalog entry 273.
    ScriptPushProtocolNotPersistent = 273,
    /// Catalog entry 274.
    HintScriptPushProtocolNotPersistent = 274,
    /// Catalog entry 275.
    SideServerCallsClientOnlyFfi = 275,
    /// Catalog entry 276.
    HintSideServerCallsClientOnlyFfi = 276,
    /// Catalog entry 277.
    SqlTablePrimaryKeyNotKnownString = 277,
    /// Catalog entry 278.
    HintSqlTablePrimaryKeyNotKnownString = 278,
    /// Catalog entry 279.
    SqlViewNotPlainString = 279,
    /// Catalog entry 280.
    HintSqlViewNotPlainStringStrcat = 280,
    /// Catalog entry 281.
    HintSqlViewNotPlainStringLiteral = 281,
    /// Catalog entry 282.
    CjrizeFunctionNotExplicitAtCodegen = 282,
    /// Catalog entry 283.
    CjrizeTaskKindNotFullyDetermined = 283,
    /// Catalog entry 284.
    CjrizeInitializerNotFullyDetermined = 284,
    /// Catalog entry 285.
    CorifyUnknownTypeNameInModulePath = 285,
    /// Catalog entry 286.
    CorifyUnknownPatternConstructorId = 286,
    /// Catalog entry 287.
    CorifyUnknownDataConstructorInModulePath = 287,
    /// Catalog entry 288.
    JscompInternalStrcatInvariant = 288,
    /// Catalog entry 289.
    JscompUnurlifyUnknownType = 289,
    /// Catalog entry 290.
    JscompUnsupportedFfiValueInJs = 290,
    /// Catalog entry 291.
    JscompUnsupportedFfiCallInJs = 291,
    /// Catalog entry 292.
    JscompUnknownUnaryOperatorInJs = 292,
    /// Catalog entry 293.
    JscompUnknownBinaryOperatorInJs = 293,
    /// Catalog entry 294.
    JscompClientConstructUnsupportedInJs = 294,
    /// Catalog entry 295.
    SideGetenvNotCompileTimeString = 295,
    /// Catalog entry 296.
    HintSideGetenvNotCompileTimeString = 296,
    /// Catalog entry 297.
    UrpLibraryProjectParseFailed = 297,
    /// Catalog entry 298.
    UrpUnrecognizedDirective = 298,
    /// Catalog entry 299.
    CompilerInternalLockPoisoned = 299,
    /// Catalog entry 300.
    CoreEspecializeMissingSpecializationMetadata = 300,
    /// Catalog entry 301.
    CoreLocalReductionStaticCaseArmMissing = 301,
    /// Catalog entry 302.
    CliManifestMissingOrchestrator = 302,
    /// Catalog entry 303.
    CliManifestMissingFmt = 303,
    /// Catalog entry 304.
    CliManifestEntryRequired = 304,
    /// Catalog entry 305.
    CliUrTomlReadFailed = 305,
    /// Catalog entry 306.
    CliUrTomlParseFailed = 306,
    /// Catalog entry 307.
    CliUrTomlMissingInstall = 307,
    /// Catalog entry 308.
    CliManifestDatabaseEngineInvalid = 308,
    /// Catalog entry 309.
    CliPeerBinaryNotFound = 309,
    /// Catalog entry 310.
    CliScssCompilationFailed = 310,
    /// Catalog entry 311.
    CliOrchestratorScssCompiling = 311,
    /// Catalog entry 312.
    CliOrchestratorBuildingApp = 312,
    /// Catalog entry 313.
    CliOrchestratorTypeCheckingLib = 313,
    /// Catalog entry 314.
    CliOrchestratorUsageMoreHelp = 314,
    /// Catalog entry 315.
    CliDispatchMissingSubcommand = 315,
    /// Catalog entry 316.
    CliDispatchRunHelpHint = 316,
    /// Catalog entry 317.
    CliUsageHeading = 317,
    /// Catalog entry 318.
    CliOrchestratorUsageLines = 318,
    /// Catalog entry 319.
    CliUrCompileHelpExtra = 319,
    /// Catalog entry 320.
    CliUrFmtHelp = 320,
    /// Catalog entry 321.
    CliUrFmtNoSourceFilesFound = 321,
    /// Catalog entry 322.
    CliUrFmtProjectUrpNotFound = 322,
    /// Catalog entry 323.
    CliUrFmtUnknownFlag = 323,
    /// Catalog entry 324.
    CliUrFmtNotUrFile = 324,
    /// Catalog entry 325.
    CliUrFmtFileMissing = 325,
    /// Catalog entry 326.
    CliUrFmtReadFailed = 326,
    /// Catalog entry 327.
    CliUrFmtCheckWouldChange = 327,
    /// Catalog entry 328.
    CliUrFmtWriteFailed = 328,
    /// Catalog entry 329.
    CliUrFmtParseFailedHeader = 329,
    /// Catalog entry 330.
    CliInstallPackagePresent = 330,
    /// Catalog entry 331.
    CliInstallInProgress = 331,
    /// Catalog entry 332.
    CliInstallSucceeded = 332,
    /// Catalog entry 333.
    CliInstallUrpHint = 333,
    /// Catalog entry 334.
    CliInstallGitFailed = 334,
    /// Catalog entry 335.
    CliInstallUsage = 335,
    /// Catalog entry 336.
    CliDaemonStopped = 336,
    /// Catalog entry 337.
    CliDaemonNotImplemented = 337,
    /// Catalog entry 338.
    CliDaemonUsage = 338,
    /// Catalog entry 339.
    CliUrNewCreated = 339,
    /// Catalog entry 340.
    CliUrNewGitNote = 340,
    /// Catalog entry 341.
    CliUrNewBuildHint = 341,
    /// Catalog entry 342.
    CliUrNewUsageApp = 342,
    /// Catalog entry 343.
    CliUrNewUsageLib = 343,
    /// Catalog entry 344.
    CliDemoRequiresDirectory = 344,
    /// Catalog entry 345.
    CliNoProjectSeeHelp = 345,
    /// Catalog entry 346.
    CliInvalidLimitNumber = 346,
    /// Catalog entry 347.
    CliUnknownCompilerFlag = 347,
    /// Catalog entry 348.
    CliCompilerWorkerSpawnFailed = 348,
    /// Catalog entry 349.
    CliCompilerWorkerPanicked = 349,
    /// Catalog entry 350.
    CliCompilerPhaseTiming = 350,
    /// Catalog entry 351.
    CliDumpOutputUsage = 351,
    /// Catalog entry 352.
    CliDumpOutputChdirFailed = 352,
    /// Catalog entry 353.
    CliDumpOutputCompileFailed = 353,
    /// Catalog entry 354.
    CliTestParseHasErrors = 354,
    /// Catalog entry 355.
    CliTestParseDeclCount = 355,
    /// Catalog entry 356.
    CliTestParseFailed = 356,
    /// Catalog entry 357.
    CliTestParseTwoDecls = 357,
    /// Catalog entry 358.
    CliTestParseTwoDeclsFailed = 358,
    /// Catalog entry 359.
    CliTestPpContextOk = 359,
    /// Catalog entry 360.
    CliFileReadFailed = 360,
    /// Catalog entry 361.
    CliTomlParseAtPathFailed = 361,
    /// Catalog entry 362.
    CliPackageLanguageInvalid = 362,
    /// Catalog entry 363.
    CliBuildDatabaseEngineMismatch = 363,
    /// Catalog entry 364.
    CliProjectNameEmpty = 364,
    /// Catalog entry 365.
    CliProjectNameMustStartWithLetter = 365,
    /// Catalog entry 366.
    CliProjectNameInvalidCharacters = 366,
    /// Catalog entry 367.
    CliUrNewDirectoryExists = 367,
    /// Catalog entry 368.
    CliUrNewScaffoldIoFailed = 368,
    /// Catalog entry 369.
    CliDatabaseBackendCliRejected = 369,
    /// Catalog entry 370.
    CliCompileResourceLimitConfiguration = 370,
    /// Catalog entry 371.
    CliDemoModeFailed = 371,
    /// Catalog entry 372.
    CliLspRunFailed = 372,
    /// Catalog entry 373.
    CliLspProjectOpenFailed = 373,
    /// Catalog entry 374.
    CliLspWorkspaceChdirFailed = 374,
    /// Catalog entry 375.
    CliLspWorkspaceReadDirFailed = 375,
    /// Catalog entry 376.
    CliLspWorkspaceDirEntryFailed = 376,
    /// Catalog entry 377.
    CliLspWorkspaceNoUrProjectFile = 377,
    /// Catalog entry 378.
    CliLspWorkspaceUrpPathInternal = 378,
    /// Catalog entry 379.
    CliLspWorkspaceMultipleUrProjectFiles = 379,
    /// Catalog entry 380.
    CliLspProjectResolveFailed = 380,
    /// Catalog entry 381.
    CliCompileStoppedAfterDiagnostics = 381,
    /// Catalog entry 382.
    CliCCompilerRejectedGeneratedFile = 382,
    /// Catalog entry 383.
    CliLinkerCouldNotProduceExecutable = 383,
    /// Catalog entry 384.
    CliWriteGeneratedCFileFailed = 384,
    /// Catalog entry 385.
    CliToolBannerCompileStopped = 385,
    /// Catalog entry 386.
    CliToolBannerCBuild = 386,
    /// Catalog entry 387.
    CliToolBannerLink = 387,
    /// Catalog entry 388.
    CliCompileWriteSqlFileFailed = 388,
    /// Catalog entry 389.
    CliUrpDirectiveParseFailed = 389,
    /// Catalog entry 390.
    CliUrpInvalidUnsignedIntegerDirective = 390,
    /// Catalog entry 391.
    CliSubprocessSpawnFailed = 391,
    /// Catalog entry 392.
    CliSubprocessPollFailed = 392,
    /// Catalog entry 393.
    CliSubprocessRunFailed = 393,
    /// Catalog entry 394.
    CliCompilerCcLinkTestDeadlineExceeded = 394,
    /// Catalog entry 395.
    CliUrpFfiExpectedModuleDotFunc = 395,
    /// Catalog entry 396.
    CliUrpFfiMapExpectedModuleFuncEquals = 396,
    /// Catalog entry 397.
    CliUrpUnknownRewritePathKind = 397,
    /// Catalog entry 398.
    CliUrpOnErrorNeedsQualifiedName = 398,
    /// Catalog entry 399.
    CliUrpRewriteBadSyntax = 399,
    /// Catalog entry 400.
    CliUrpAllowBadSyntax = 400,
    /// Catalog entry 401.
    CliUrpDenyBadSyntax = 401,
    /// Catalog entry 402.
    CliUrpUnknownFilterKind = 402,
    /// Catalog entry 403.
    CliUrpLibraryNotFound = 403,
    /// Catalog entry 404.
    CliDebuggerGdbStdoutClosed = 404,
    /// Catalog entry 405.
    CliDebuggerGdbLineQueueMutexPoisoned = 405,
    /// Catalog entry 406.
    CliDebuggerGdbMiReported = 406,
    /// Catalog entry 407.
    CliDebuggerSpawnMiBackendFailed = 407,
    /// Catalog entry 408.
    CliDebuggerSetVariableNameNotSimpleCIdentifier = 408,
    /// Catalog entry 409.
    CliDebuggerDapStaleVariablesReference = 409,
    /// Catalog entry 410.
    CliDebuggerDapVarCreateFailed = 410,
    /// Catalog entry 411.
    CliDebuggerDapNotVariableContainer = 411,
    /// Catalog entry 412.
    CliDebuggerDapFieldNotFound = 412,
    /// Catalog entry 413.
    CliDebuggerDapNoLaunchBeforeConfigurationDone = 413,
    /// Catalog entry 414.
    CliDebuggerDapAttachFailed = 414,
    /// Catalog entry 415.
    CliDebuggerDapLoadSymbolsFailed = 415,
    /// Catalog entry 416.
    CliDebuggerDapRunInferiorFailed = 416,
    /// Catalog entry 417.
    CliDebuggerDapGdbSessionMissing = 417,
    /// Catalog entry 418.
    CliDebuggerDapRequestBeforeLaunch = 418,
    /// Catalog entry 419.
    CliDebuggerDapReadSourceFailed = 419,
    /// Catalog entry 420.
    CliDebuggerDapDisassembleNeedsMemoryReference = 420,
    /// Catalog entry 421.
    CliDebuggerDapSourceRequiresPathProperty = 421,
    /// Catalog entry 422.
    CliDebuggerDapAttachRequiresProcessId = 422,
    /// Catalog entry 423.
    CliDebuggerDapLaunchRequiresProgram = 423,
    /// Catalog entry 424.
    CliDebuggerDapExceptionNoSignalDetailsThisThread = 424,
    /// Catalog entry 425.
    CliDebuggerDapExceptionNoInformation = 425,
    /// Catalog entry 426.
    CliDebuggerDapBreakpointPendingAfterConfigurationDone = 426,
    /// Catalog entry 427.
    CliDebuggerDapBreakpointGdbCouldNotSet = 427,
    /// Catalog entry 428.
    CliDebuggerDapStoppedSignalLabel = 428,
    /// Catalog entry 429.
    CliDebuggerDapExceptionDeliveredSignalDescription = 429,
    /// Catalog entry 430.
    CliDebuggerDapThreadDisplayName = 430,
    /// Catalog entry 431.
    CliDebuggerDapScopeLocalsName = 431,
    /// Catalog entry 432.
    CliDebuggerDapFilterLabelFatalSignals = 432,
    /// Catalog entry 433.
    CliDebuggerDapFilterLabelAllSignals = 433,
    /// Catalog entry 434.
    CliDebuggerDapFilterLabelCppThrow = 434,
    /// Catalog entry 435.
    CliDebuggerUnknownFlag = 435,
    /// Catalog entry 436.
    CliDebuggerMissingMode = 436,
    /// Catalog entry 437.
    CliDebuggerCliDapStdioFailed = 437,
    /// Catalog entry 438.
    CliDebuggerCliTtyRequiresProgramPath = 438,
    /// Catalog entry 439.
    CliDebuggerRunFailed = 439,
    /// Catalog entry 440.
    CliDebuggerGdbSpawnFailed = 440,
    /// Catalog entry 441.
    CliDebuggerGdbExecFailed = 441,
    /// Catalog entry 442.
    CliDebuggerGdbExitedNonZero = 442,
    /// Catalog entry 443.
    CliDebuggerUsageBody = 443,
    /// Catalog entry 444.
    CliDevPreprocessWindowFailed = 444,
    /// Catalog entry 445.
    CliPhaseIncompleteNoOutput = 445,
    /// Catalog entry 446.
    CliDebuggerGdbMiDriverLoopExhausted = 446,
    /// Catalog entry 447.
    CliDebuggerDapStdioLoopExhausted = 447,
}
