#!/bin/sh
# Generate build.ninja for Ur/Web.
# Called by configure with variables: srcdir builddir prefix BIN LIB SRCLIB INCLUDE
# CC MLTON NINJA BEARSSL_* LIBUNISTRING_* PTHREAD_* BEARSSL_USE_VENDOR

: "${srcdir:=.}"
: "${builddir:=.}"
: "${prefix:=/usr/local}"
: "${BIN:=$prefix/bin}"
: "${LIB:=$prefix/lib}"
: "${MANDIR:=$prefix/share/man}"
: "${SRCLIB:=$prefix/lib/urweb}"
: "${INCLUDE:=$prefix/include/urweb}"
: "${CC:=gcc}"
: "${MLTON:=mlton}"
: "${MLLEX:=mllex}"
: "${MLYACC:=mlyacc}"
: "${BEARSSL_INCLUDES:=}"
: "${BEARSSL_LDFLAGS:=}"
: "${BEARSSL_LIBS:=-lbearssl}"
: "${BEARSSL_USE_VENDOR:=0}"
: "${LIBUNISTRING_INCLUDES:=}"
: "${LIBUNISTRING_LIBS:=-lunistring}"
: "${PTHREAD_CFLAGS:=-pthread}"
: "${PTHREAD_LIBS:=-pthread}"

case "$(uname -s)" in
  Darwin*) SHLIB_EXT=".dylib" ;;
  *)       SHLIB_EXT=".so" ;;
esac

# C include path: need config.h from builddir
CPPFLAGS="-I\$builddir/include/urweb -I\$srcdir/include/urweb \$BEARSSL_INCLUDES \$LIBUNISTRING_INCLUDES \$PTHREAD_CFLAGS"
CFLAGS="-std=c11 -pedantic -Wall -Wunused-parameter -Werror -Wno-format-security -Wno-deprecated-declarations -Wno-overlength-strings -Wno-gnu-statement-expression -Wno-gnu-zero-variadic-macro-arguments -Wno-pedantic -U_FORTIFY_SOURCE"

cat <<'GENEOF'
# Ur/Web build.ninja - generated by scripts/gen_build.ninja.sh

GENEOF

# Emit variables (single-quote in the heredoc prevents expansion; we need the values)
echo "srcdir = $srcdir"
echo "builddir = ."
echo "prefix = $prefix"
echo "BIN = $BIN"
echo "LIB = $LIB"
echo "MANDIR = $MANDIR"
echo "SRCLIB = $SRCLIB"
echo "INCLUDE = $INCLUDE"
echo "CC = $CC"
echo "MLTON = $MLTON"
echo "MLLEX = $MLLEX"
echo "MLYACC = $MLYACC"
echo "BEARSSL_INCLUDES = $BEARSSL_INCLUDES"
echo "BEARSSL_LDFLAGS = $BEARSSL_LDFLAGS"
echo "BEARSSL_LIBS = $BEARSSL_LIBS"
echo "BEARSSL_USE_VENDOR = $BEARSSL_USE_VENDOR"
echo "LIBUNISTRING_INCLUDES = $LIBUNISTRING_INCLUDES"
echo "LIBUNISTRING_LIBS = $LIBUNISTRING_LIBS"
echo "PTHREAD_CFLAGS = $PTHREAD_CFLAGS"
echo "PTHREAD_LIBS = $PTHREAD_LIBS"
echo "CPPFLAGS = -I\$builddir/include/urweb -I\$srcdir/include/urweb \$BEARSSL_INCLUDES \$LIBUNISTRING_INCLUDES \$PTHREAD_CFLAGS"
echo "CFLAGS = $CFLAGS"
echo "SHLIB_EXT = $SHLIB_EXT"
echo ""

cat <<'NINJAEOF'

# Rules
rule mllex
  command = cd $builddir/src && cp $srcdir/src/urweb.lex urweb.mlton.lex && $MLLEX urweb.mlton.lex
  description = mllex urweb.lex -> urweb.mlton.lex.sml

rule mlyacc
  command = cd $builddir/src && cp $srcdir/src/urweb.grm urweb.mlton.grm && $MLYACC urweb.mlton.grm
  description = mlyacc urweb.grm

rule mlton
  command = $MLTON -mlb-path-var 'SRC $srcdir/src' -mlb-path-var 'BUILD $builddir/src' -output $out $in
  description = MLton $out

rule mlton_compiler
  command = sh $srcdir/scripts/mlton-with-progress.sh $MLTON -mlb-path-var 'SRC $srcdir/src' -mlb-path-var 'BUILD $builddir/src' -output $out $in
  description = MLton compiler (2-3 min)
  pool = console

rule cc
  command = $CC $CPPFLAGS $CFLAGS -c $in -o $out
  description = CC $out

rule link_so
  command = $CC -shared $BEARSSL_LDFLAGS $PTHREAD_LIBS -lm $BEARSSL_LIBS $LIBUNISTRING_LIBS -o $out $in
  description = LINK $out

rule run
  command = $in $out
  description = RUN $in

rule gen_mlb
  command = sed -e 's/^\(.*\)\.grm$$/$$(BUILD)\/\1.mlton.grm.sig:\1.mlton.grm.sml/' -e 'y/:/\n/' -e 's/^\(.*\)\.lex$$/$$(BUILD)\/\1.mlton.lex.sml/' $in | cat $srcdir/src/prefix.mlb - $srcdir/src/suffix.mlb > $out
  description = Generate urweb.mlb

rule entities
  command = $in $srcdir/xml/xhtml-lat1.ent $srcdir/xml/xhtml-special.ent $srcdir/xml/xhtml-symbol.ent > $out
  description = Generate entities.sml

# BearSSL (vendored) - only when BEARSSL_USE_VENDOR=1

NINJAEOF

if test "$BEARSSL_USE_VENDOR" = "1"; then
  cat <<'NINJABEAR'
rule build_bearssl
  command = echo "[$$(date +%H:%M:%S)] Building BearSSL..." && make -C $srcdir/vendor/BearSSL 2>&1 | sed 's/^/  /' && echo "[$$(date +%H:%M:%S)] BearSSL done."
  description = Build vendored BearSSL
  pool = console

build bearssl: build_bearssl

NINJABEAR
fi

cat <<'NINJAEOF'

# xml/parse
build $builddir/xml/parse: mlton $srcdir/xml/parse.sml

# xml/entities.sml
build $builddir/xml/entities.sml: entities $builddir/xml/parse

# Lexer/parser
build $builddir/src/urweb.mlton.lex.sml: mllex $srcdir/src/urweb.lex

build $builddir/src/urweb.mlton.grm.sig $builddir/src/urweb.mlton.grm.sml: mlyacc $srcdir/src/urweb.grm

# urweb.mlb (order-only: grm.sig, grm.sml, lex.sml must exist first)
rule gen_mlb2
  command = (echo '$$(SML_LIB)/basis/basis.mlb'; echo '$$(SML_LIB)/basis/mlton.mlb'; echo ''; echo '$$(BUILD)/urweb.mlb'; echo ''; echo 'main.mlton.sml') > $out
  description = Generate compiler.mlb placeholder

# Actually we use the existing compiler.mlb. The urweb.mlb is generated from sources.
rule mk_urweb_mlb
  command = sed -e 's/^\(.*\)\.grm$$/$$(BUILD)\/\1.mlton.grm.sig:\1.mlton.grm.sml/' -e 'y/:/\n/' -e 's/^\(.*\)\.lex$$/$$(BUILD)\/\1.mlton.lex.sml/' $srcdir/src/prefix.mlb $srcdir/src/sources $srcdir/src/suffix.mlb > $out
  description = Generate urweb.mlb

build $builddir/src/urweb.mlb: mk_urweb_mlb $srcdir/src/sources $srcdir/src/prefix.mlb $srcdir/src/suffix.mlb

# C object files
NINJAEOF

# C sources for liburweb
CSOURCES="memmem.c crypto.c urweb.c request.c queue.c"
for c in $CSOURCES; do
  echo "build \$builddir/src/c/${c%.c}.o: cc \$srcdir/src/c/$c"
done

# Protocol C sources (http, cgi, fastcgi, static)
PROTOCOLS="http cgi fastcgi static"
for c in $PROTOCOLS; do
  echo "build \$builddir/src/c/${c}.o: cc \$srcdir/src/c/${c}.c"
done

cat <<'NINJAEOF2'

# liburweb (static - we use .a for simplicity; shared libs need more setup)
rule ar
  command = ar crs $out $in
  description = AR $out

NINJAEOF2

OBJS=""
for c in $CSOURCES; do
  OBJS="$OBJS \$builddir/src/c/${c%.c}.o"
done
echo "build \$builddir/src/c/liburweb.a: ar $OBJS"
echo ""
for p in $PROTOCOLS; do
  echo "build \$builddir/src/c/liburweb_${p}.a: ar \$builddir/src/c/${p}.o"
done
echo "build runtime: phony \$builddir/src/c/liburweb.a \$builddir/src/c/liburweb_http.a \$builddir/src/c/liburweb_cgi.a \$builddir/src/c/liburweb_fastcgi.a \$builddir/src/c/liburweb_static.a"
echo ""

# Install (DESTDIR supported). Use cp+chmod instead of install (POSIX portable)
echo "rule install_cmd"
echo "  command = DESTDIR=\"\$\${DESTDIR:-}\" ; mkdir -p \"\$\$DESTDIR$BIN\" \"\$\$DESTDIR$LIB\" \"\$\$DESTDIR$MANDIR/man1\" \"\$\$DESTDIR$SRCLIB/ur\" \"\$\$DESTDIR$SRCLIB/js\" \"\$\$DESTDIR$INCLUDE\" && cp $builddir/bin/urweb \"\$\$DESTDIR$BIN/urweb\" && chmod 755 \"\$\$DESTDIR$BIN/urweb\" && cp $builddir/src/c/liburweb.a \"\$\$DESTDIR$LIB/\" && cp $builddir/src/c/liburweb_http.a $builddir/src/c/liburweb_cgi.a $builddir/src/c/liburweb_fastcgi.a $builddir/src/c/liburweb_static.a \"\$\$DESTDIR$LIB/\" && cp $srcdir/lib/ur/*.urs \"\$\$DESTDIR$SRCLIB/ur/\" && cp $srcdir/lib/ur/*.ur \"\$\$DESTDIR$SRCLIB/ur/\" && cp $srcdir/lib/js/*.js \"\$\$DESTDIR$SRCLIB/js/\" && cp $srcdir/include/urweb/*.h \"\$\$DESTDIR$INCLUDE/\" && cp $srcdir/doc/urweb.1 \"\$\$DESTDIR$MANDIR/man1/\" && (cp $builddir/include/urweb/config.h \"\$\$DESTDIR$INCLUDE/\" 2>/dev/null || true)"
echo "  description = Install Ur/Web"
echo ""
echo "build install: install_cmd | $builddir/bin/urweb $builddir/src/c/liburweb.a $builddir/src/c/liburweb_http.a $builddir/src/c/liburweb_cgi.a $builddir/src/c/liburweb_fastcgi.a $builddir/src/c/liburweb_static.a $srcdir/doc/urweb.1"
echo ""

# Uninstall (DESTDIR supported, must match install prefix)
echo "rule uninstall_cmd"
echo "  command = DESTDIR=\"\$\${DESTDIR:-}\" ; rm -f \"\$\$DESTDIR$BIN/urweb\" \"\$\$DESTDIR$LIB/liburweb.a\" \"\$\$DESTDIR$LIB/liburweb_http.a\" \"\$\$DESTDIR$LIB/liburweb_cgi.a\" \"\$\$DESTDIR$LIB/liburweb_fastcgi.a\" \"\$\$DESTDIR$LIB/liburweb_static.a\" \"\$\$DESTDIR$MANDIR/man1/urweb.1\" && rm -f \"\$\$DESTDIR$SRCLIB/ur/\"*.urs \"\$\$DESTDIR$SRCLIB/ur/\"*.ur \"\$\$DESTDIR$SRCLIB/js/\"*.js \"\$\$DESTDIR$INCLUDE/\"*.h \"\$\$DESTDIR$INCLUDE/config.h\""
echo "  description = Uninstall Ur/Web"
echo ""
echo "build uninstall: uninstall_cmd"
echo ""

# ── FORCE: always-dirty phony, making dependents always rebuild ───────────────
cat <<'NINJAFORCE'
# FORCE: always dirty — any target that depends on FORCE always rebuilds.
build FORCE: phony

NINJAFORCE

# ── samu / samu ml — build ML compiler (always rebuilds) ─────────────────────
cat <<'NINJAML'
rule ml_build_rule
  command = sh $srcdir/scripts/mlton-with-progress.sh $MLTON -mlb-path-var 'SRC $srcdir/src' -mlb-path-var 'BUILD $srcdir/src' -output $builddir/bin/urweb $srcdir/src/compiler.mlb
  description = Build ML compiler — bin/urweb (2-3 min)
  pool = console

build ml: ml_build_rule $srcdir/src/compiler.mlb | FORCE $builddir/src/config.sml $builddir/xml/entities.sml $builddir/src/urweb.mlb

NINJAML

# ── samu test — test ML compiler ─────────────────────────────────────────────
echo "rule ml_test_rule"
echo "  command = sh \$srcdir/scripts/run-tests.sh \$srcdir \$builddir"
echo "  description = Run ML compiler tests"
echo "  pool = console"
echo ""
echo "build test: ml_test_rule | ml runtime"
echo ""

# ── samu rust — build Rust compiler (always rebuilds) ────────────────────────
echo "rule rust_build_rule"
echo "  command = cd \$srcdir && CARGO_TARGET_DIR=\$srcdir/target cargo build --release && mkdir -p \$builddir/bin && cp \$srcdir/target/release/ur-compile \$builddir/bin/urweb-rust && chmod 755 \$builddir/bin/urweb-rust"
echo "  description = Build Rust compiler — bin/urweb-rust"
echo "  pool = console"
echo ""
echo "build rust: rust_build_rule | FORCE"
echo ""

# ── samu rust-test — executable integration suite with Rust compiler ───────────
echo "rule rust_test_rule"
echo "  command = sh \$srcdir/scripts/run-tests-rust.sh \$srcdir \$builddir"
echo "  description = Run executable integration suite with URWEB=urweb-rust"
echo "  pool = console"
echo ""
echo "build rust-test: rust_test_rule | rust runtime"
echo ""

# ── samu compare — compare ML and Rust compiler output ───────────────────────
echo "rule compare_rule"
echo "  command = sh \$srcdir/scripts/compare-compilers.sh \$srcdir \$builddir"
echo "  description = Compare ML vs Rust compiler output (pretty diff)"
echo "  pool = console"
echo ""
echo "build compare: compare_rule | ml rust"
echo ""

# ── Extras ────────────────────────────────────────────────────────────────────

# Out-of-tree build: copy lib to builddir (no symlinks)
if [ "$builddir" != "$srcdir" ]; then
  echo "rule copy_lib"
  echo "  command = mkdir -p \$builddir/lib/ur \$builddir/lib/js && cp -r \$srcdir/lib/ur/* \$builddir/lib/ur/ && cp -r \$srcdir/lib/js/* \$builddir/lib/js/ && touch \$builddir/lib/.stamp"
  echo "  description = Copy lib to build dir (out-of-tree)"
  echo ""
  echo "build \$builddir/lib/.stamp: copy_lib"
  echo ""
fi

# Default: build ML compiler
echo "default ml"
