//! Shared CLI helpers and templates used by ur and sub-binaries.

use serde::Deserialize;

// ---------------------------------------------------------------------------
// Project scaffolding templates
// ---------------------------------------------------------------------------

pub const CURSOR_MD: &str = "# Ur/Web - Cursor AI Context\n\
\n\
This file provides context for AI assistants working with Ur/Web projects.\n\
For Cursor, you may copy this into `.cursor/rules/ur.mdc`.\n\
\n\
## Language Overview\n\
\n\
- **Ur** is an ML/Haskell-style language: functional, pure, strict, statically typed\n\
- **Ur/Web** = Ur + web/SQL standard library\n\
- **Key guarantee:** Well-typed programs avoid code injection, invalid HTML, dead links,\n\
  form/handler mismatches, invalid SQL, and marshaling errors\n";

pub const CLAUDE_MD: &str = "# Ur/Web - Claude AI Context\n\
\n\
This file provides context for Claude and other AI assistants working with Ur/Web projects.\n\
\n\
## Language Overview\n\
\n\
- **Ur** is an ML/Haskell-style language: functional, pure, strict, statically typed\n\
- **Ur/Web** = Ur + web/SQL standard library\n\
- **Key guarantee:** Well-typed programs avoid code injection, invalid HTML, dead links,\n\
  form/handler mismatches, invalid SQL, and marshaling errors\n";

pub const GITIGNORE: &str = "# Compiled executables\n\
*.exe\n\
\n\
# SQLite databases and generated SQL schemas\n\
*.db\n\
*.sql\n\
\n\
# ur daemon socket\n\
.ur_daemon\n";

pub const GITIGNORE_APP_SUFFIX: &str = "\n\
# Compiled CSS (regenerated by 'ur build' from style/scss/)\n\
style/css/*.css\n";

pub const URP_DIRECTIVE_KEYWORDS: &[&str] = &[
    "database",
    "sql",
    "prefix",
    "rewrite",
    "file",
    "library",
    "link",
    "ffi",
    "effectful",
    "benignEffectful",
    "clientOnly",
    "serverOnly",
    "jsFunc",
    "timeout",
    "sigfile",
    "debug",
];

// ---------------------------------------------------------------------------
// Project kind and validation
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProjectKind {
    App,
    Library,
}

pub fn validate_project_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("project name cannot be empty".into());
    }
    if !name.chars().next().map_or(false, |c| c.is_alphabetic()) {
        return Err(format!("project name must start with a letter: '{}'", name));
    }
    if !name.chars().all(|c| c.is_alphanumeric() || c == '_') {
        return Err(format!(
            "project name must contain only letters, digits, or underscores: '{}'",
            name
        ));
    }
    Ok(())
}

pub fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => {
            let mut out = c.to_uppercase().collect::<String>();
            out.push_str(chars.as_str());
            out
        }
    }
}

pub fn kind_specific_created_files(kind: ProjectKind, name: &str) -> Vec<String> {
    let mut out = vec![];
    if kind == ProjectKind::Library {
        out.push(format!("{name}/{name}.urs"));
    }
    if kind == ProjectKind::App {
        out.push(format!("{name}/style/scss/main.scss"));
        out.push(format!("{name}/style/css/main.css"));
    }
    out
}

// ---------------------------------------------------------------------------
// TOML
// ---------------------------------------------------------------------------

/// Project manifest with **closed** tables: extra keys are rejected (LangSec-style trust boundary).
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UrTomlStrict {
    pub package: UrTomlPackageStrict,
    pub build: UrTomlBuildStrict,
    #[serde(default)]
    pub style: Option<UrTomlStyleStrict>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UrTomlPackageStrict {
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default = "default_pkg_kind")]
    pub kind: String,
}

fn default_pkg_kind() -> String {
    "app".into()
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UrTomlBuildStrict {
    pub entry: String,
    #[serde(default = "default_build_db")]
    pub db: String,
    #[serde(default)]
    pub ccompiler: String,
    #[serde(default)]
    pub boot: bool,
}

fn default_build_db() -> String {
    "sqlite".into()
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UrTomlStyleStrict {
    #[serde(default)]
    pub scss: Option<String>,
    #[serde(default)]
    pub css: Option<String>,
}

pub fn parse_ur_toml_strict(content: &str) -> Result<UrTomlStrict, String> {
    toml::from_str(content).map_err(|e| format!("{e}"))
}

pub fn parse_toml(content: &str) -> Vec<(String, String)> {
    let mut section = String::new();
    let mut entries = vec![];
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line.starts_with('[') && line.ends_with(']') {
            section = line[1..line.len() - 1].trim().to_string();
            continue;
        }
        if let Some(eq) = line.find('=') {
            let key = line[..eq].trim();
            let raw_val = line[eq + 1..].trim();
            let val = if raw_val.starts_with('"') && raw_val.ends_with('"') && raw_val.len() >= 2 {
                raw_val[1..raw_val.len() - 1].to_string()
            } else {
                raw_val.to_string()
            };
            let full_key = if section.is_empty() {
                key.to_string()
            } else {
                format!("{}.{}", section, key)
            };
            entries.push((full_key, val));
        }
    }
    entries
}

pub fn toml_get<'a>(entries: &'a [(String, String)], key: &str) -> Option<&'a str> {
    entries
        .iter()
        .find(|(k, _)| k == key)
        .map(|(_, v)| v.as_str())
}

// ---------------------------------------------------------------------------
// File and flag helpers
// ---------------------------------------------------------------------------

pub fn file_exists(path: &str) -> bool {
    std::path::Path::new(path).exists()
}

/// Last path segment of an `author/repo` install spec, ignoring empty `//` segments.
pub fn package_spec_repo_leaf(spec: &str) -> &str {
    spec.split('/')
        .filter(|s| !s.is_empty())
        .last()
        .unwrap_or(spec)
}

pub fn is_file_arg(arg: &str) -> bool {
    !arg.starts_with('-')
}

pub fn should_skip_urp_line(line: &str) -> bool {
    line.is_empty() || line.starts_with('#')
}

pub fn is_unknown_compiler_flag(flag: &str, arg: &str) -> bool {
    flag.is_empty() || arg.starts_with('-')
}

pub fn is_valid_limit(n: i32) -> bool {
    n >= 0
}

pub fn command_succeeded(status: &std::io::Result<std::process::ExitStatus>) -> bool {
    status.as_ref().map_or(false, |s| s.success())
}

// ---------------------------------------------------------------------------
// Build config helpers
// ---------------------------------------------------------------------------

pub fn is_lib_project(kind: &str) -> bool {
    kind == "lib"
}

pub fn parse_boot(value: &str) -> bool {
    value == "true"
}

pub fn should_add_ccompiler(cc: &str) -> bool {
    !cc.is_empty()
}

pub fn sass_tool_available(has_sass: bool, has_sassc: bool) -> bool {
    has_sass || has_sassc
}

pub fn has_sass_or_sassc() -> bool {
    let has_sass = std::process::Command::new("which")
        .arg("sass")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map_or(false, |s| s.success());
    let has_sassc = std::process::Command::new("which")
        .arg("sassc")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map_or(false, |s| s.success());
    sass_tool_available(has_sass, has_sassc)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compiler_diagnostics::lock_for_compile;
    use std::sync::Mutex;

    static CWD_LOCK: Mutex<()> = Mutex::new(());

    #[test]
    fn validate_name_empty() {
        assert!(validate_project_name("").is_err());
    }

    #[test]
    fn validate_name_starts_with_digit() {
        assert!(validate_project_name("1foo").is_err());
    }

    #[test]
    fn validate_name_valid() {
        assert!(validate_project_name("my_app").is_ok());
        assert!(validate_project_name("Foo123").is_ok());
    }

    #[test]
    fn validate_name_hyphen_invalid() {
        assert!(validate_project_name("my-app").is_err());
    }

    #[test]
    fn ur_toml_strict_accepts_new_project_shape() {
        let content = r#"[package]
name = "demo"
kind = "app"

[build]
entry = "demo"
db = "sqlite"
ccompiler = "gcc"
boot = false

[style]
scss = "style/scss/main.scss"
css = "style/css/main.css"
"#;
        let cfg = parse_ur_toml_strict(content).expect("valid ur.toml");
        assert_eq!(cfg.package.kind, "app");
        assert_eq!(cfg.build.entry, "demo");
        assert!(cfg.style.is_some());
    }

    #[test]
    fn ur_toml_strict_accepts_library_template_shape() {
        let content = r#"[package]
name = "mylib"
kind = "lib"

[build]
entry = "mylib"
boot = false
"#;
        assert!(parse_ur_toml_strict(content).is_ok());
    }

    #[test]
    fn ur_toml_strict_rejects_unknown_table_fields() {
        let content = r#"[package]
name = "x"
kind = "app"
wat = true

[build]
entry = "m"
"#;
        assert!(parse_ur_toml_strict(content).is_err());
    }

    #[test]
    fn toml_parse_basic() {
        let content = "[build]\nentry = \"myapp\"\ndb = \"sqlite\"\n";
        let entries = parse_toml(content);
        assert_eq!(
            entries
                .iter()
                .find(|(k, _)| k == "build.entry")
                .map(|(_, v)| v.as_str()),
            Some("myapp")
        );
    }

    #[test]
    fn toml_parse_section_and_key() {
        let content = "[build]\nentry = \"x\"\n";
        let entries = parse_toml(content);
        assert_eq!(toml_get(&entries, "build.entry"), Some("x"));
    }

    #[test]
    fn toml_get_missing_returns_none() {
        let entries = parse_toml("[build]\nentry = \"x\"\n");
        assert_eq!(toml_get(&entries, "build.other"), None);
        assert_eq!(toml_get(&entries, "missing"), None);
    }

    #[test]
    fn toml_parse_empty_line_skipped() {
        let content = "[a]\n\nkey = \"v\"\n";
        let entries = parse_toml(content);
        assert_eq!(toml_get(&entries, "a.key"), Some("v"));
    }

    #[test]
    fn toml_parse_quoted_value() {
        let content = r#"[x]
k = "hello""#;
        let entries = parse_toml(content);
        assert_eq!(toml_get(&entries, "x.k"), Some("hello"));
    }

    #[test]
    fn toml_comment_ignored() {
        let content = "# comment\n[build]\nentry = \"x\"\n";
        let entries = parse_toml(content);
        assert_eq!(entries.len(), 1);
    }

    #[test]
    fn toml_line_looks_like_comment_not_parsed_as_key() {
        let content = "#key = value\n[build]\nentry = \"x\"\n";
        let entries = parse_toml(content);
        assert!(!entries.iter().any(|(k, _)| k.starts_with('#')));
        assert_eq!(toml_get(&entries, "build.entry"), Some("x"));
    }

    #[test]
    fn toml_section_bracket_requires_both() {
        let content = "[build\nentry = \"x\"\n";
        let entries = parse_toml(content);
        assert_eq!(toml_get(&entries, "entry"), Some("x"));
    }

    #[test]
    fn is_lib_project_detects_lib() {
        assert!(is_lib_project("lib"));
        assert!(!is_lib_project("app"));
        assert!(!is_lib_project(""));
    }

    #[test]
    fn parse_boot_detects_true() {
        assert!(parse_boot("true"));
        assert!(!parse_boot("false"));
        assert!(!parse_boot(""));
    }

    #[test]
    fn should_add_ccompiler_when_non_empty() {
        assert!(should_add_ccompiler("gcc"));
        assert!(!should_add_ccompiler(""));
    }

    #[test]
    fn is_file_arg_accepts_ur_without_dash() {
        assert!(is_file_arg("m.ur"));
        assert!(!is_file_arg("-check"));
    }

    #[test]
    fn should_skip_urp_line_empty_and_comments() {
        assert!(should_skip_urp_line(""));
        assert!(should_skip_urp_line("# comment"));
        assert!(!should_skip_urp_line("mymod"));
    }

    #[test]
    fn is_unknown_compiler_flag_detects_flags() {
        assert!(is_unknown_compiler_flag("", "-"));
        assert!(is_unknown_compiler_flag("bad", "-bad"));
        assert!(!is_unknown_compiler_flag("myproj", "myproj"));
    }

    #[test]
    fn is_valid_limit_non_negative() {
        assert!(is_valid_limit(0));
        assert!(is_valid_limit(1));
        assert!(!is_valid_limit(-1));
    }

    #[test]
    fn command_succeeded_ok_and_success() {
        let s = std::process::Command::new("true").status();
        assert!(command_succeeded(&s));
    }

    #[test]
    fn sass_tool_available_either_or() {
        assert!(sass_tool_available(true, false));
        assert!(sass_tool_available(false, true));
        assert!(sass_tool_available(true, true));
        assert!(!sass_tool_available(false, false));
    }

    #[test]
    fn file_exists_detects_present_and_absent() {
        let _guard = lock_for_compile(&CWD_LOCK, "cli_common file_exists test");
        let dir = tempfile::tempdir().unwrap();
        let cwd = std::env::current_dir().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();
        std::fs::write("exists.txt", "").unwrap();
        assert!(file_exists("exists.txt"));
        assert!(!file_exists("nonexistent.txt"));
        std::env::set_current_dir(&cwd).unwrap();
    }

    #[test]
    fn command_succeeded_err_fails() {
        let s = std::process::Command::new("/nonexistent").status();
        assert!(!command_succeeded(&s));
    }

    #[test]
    fn toml_unclosed_quote_preserves_raw() {
        let content = "[x]\nk = \"hello\n";
        let entries = parse_toml(content);
        let v = toml_get(&entries, "x.k").unwrap();
        assert!(v.contains("hello"), "unclosed quote should not strip");
    }

    #[test]
    fn capitalize_helper() {
        assert_eq!(capitalize("hello"), "Hello");
        assert_eq!(capitalize(""), "");
        assert_eq!(capitalize("A"), "A");
    }

    #[test]
    fn kind_specific_created_files_app() {
        let files = kind_specific_created_files(ProjectKind::App, "foo");
        assert!(files.iter().any(|s| s.contains("style/scss")));
        assert!(!files.iter().any(|s| s.ends_with(".urs")));
    }

    #[test]
    fn kind_specific_created_files_library() {
        let files = kind_specific_created_files(ProjectKind::Library, "mylib");
        assert!(files.iter().any(|s| s.ends_with(".urs")));
        assert!(!files.iter().any(|s| s.contains("style/")));
    }

    #[test]
    fn package_spec_repo_leaf_skips_empty_segments() {
        assert_eq!(package_spec_repo_leaf("org/repo"), "repo");
        assert_eq!(package_spec_repo_leaf("org//repo"), "repo");
    }
}
