//! `urweb` — Ur/Web compiler CLI
//!
//! Faithfully translates `main.mlton.sml`.  During Session 1 all compilation
//! paths are stubs (`todo!()` / `eprintln!`); the CLI structure itself is
//! complete.

use std::process;

use urweb::settings::Settings;

// ---------------------------------------------------------------------------
// Project scaffolding templates
// ---------------------------------------------------------------------------

const CURSOR_MD: &str = "# Ur/Web - Cursor AI Context\n\
\n\
This file provides context for AI assistants working with Ur/Web projects.\n\
For Cursor, you may copy this into `.cursor/rules/urweb.mdc`.\n\
\n\
## Language Overview\n\
\n\
- **Ur** is an ML/Haskell-style language: functional, pure, strict, statically typed\n\
- **Ur/Web** = Ur + web/SQL standard library\n\
- **Key guarantee:** Well-typed programs avoid code injection, invalid HTML, dead links,\n\
  form/handler mismatches, invalid SQL, and marshaling errors\n";

const CLAUDE_MD: &str = "# Ur/Web - Claude AI Context\n\
\n\
This file provides context for Claude and other AI assistants working with Ur/Web projects.\n\
\n\
## Language Overview\n\
\n\
- **Ur** is an ML/Haskell-style language: functional, pure, strict, statically typed\n\
- **Ur/Web** = Ur + web/SQL standard library\n\
- **Key guarantee:** Well-typed programs avoid code injection, invalid HTML, dead links,\n\
  form/handler mismatches, invalid SQL, and marshaling errors\n";

const GITIGNORE: &str = "# Compiled executables\n\
*.exe\n\
\n\
# SQLite databases and generated SQL schemas\n\
*.db\n\
*.sql\n\
\n\
# Urweb daemon socket\n\
.urweb_daemon\n";

const GITIGNORE_APP_SUFFIX: &str = "\n\
# Compiled CSS (regenerated by 'urweb build' from style/scss/)\n\
style/css/*.css\n";

// ---------------------------------------------------------------------------
// Version info (will be filled from config at runtime)
// ---------------------------------------------------------------------------

const VERSION_STRING: &str = env!("CARGO_PKG_VERSION");

// ---------------------------------------------------------------------------
// Subcommand: new
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ProjectKind {
    App,
    Library,
}

fn validate_project_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("project name cannot be empty".into());
    }
    if !name.chars().next().map_or(false, |c| c.is_alphabetic()) {
        return Err(format!("project name must start with a letter: '{}'", name));
    }
    if !name.chars().all(|c| c.is_alphanumeric() || c == '_') {
        return Err(format!(
            "project name must contain only letters, digits, or underscores: '{}'",
            name
        ));
    }
    Ok(())
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
    }
}

/// Returns the kind-specific created file paths for display (e.g. .urs for lib, style/ for app).
fn kind_specific_created_files(kind: ProjectKind, name: &str) -> Vec<String> {
    let mut out = vec![];
    if kind == ProjectKind::Library {
        out.push(format!("{name}/{name}.urs"));
    }
    if kind == ProjectKind::App {
        out.push(format!("{name}/style/scss/main.scss"));
        out.push(format!("{name}/style/css/main.css"));
    }
    out
}

fn write_file(path: &str, content: &str) -> std::io::Result<()> {
    std::fs::write(path, content)
}

fn new_project(kind: ProjectKind, name: &str) -> i32 {
    if let Err(e) = validate_project_name(name) {
        eprintln!("error: {}", e);
        return 1;
    }
    if std::fs::metadata(name).is_ok() {
        eprintln!("error: '{}' already exists", name);
        return 1;
    }

    if let Err(e) = std::fs::create_dir(name) {
        eprintln!("error: {}", e);
        return 1;
    }

    let mod_name = capitalize(name);

    let result: std::io::Result<()> = (|| {
        match kind {
            ProjectKind::App => {
                write_file(
                    &format!("{}/{}.urp", name, name),
                    &format!(
                        "file /style/css/main.css style/css/main.css text/css\n\n{}\n",
                        name
                    ),
                )?;
                write_file(
                    &format!("{}/{}.ur", name, name),
                    &format!(
                        "fun main () : transaction page =\n\
                    count <- source 0;\n\
                    return <xml>\n\
                    <head>\n\
                    <title>{mod}</title>\n\
                    <link rel=\"stylesheet\" href=\"/style/css/main.css\"/>\n\
                    </head>\n\
                    <body>\n\
                    <h1>Counter</h1>\n\
                    <dyn signal={{n <- signal count;\n\
                    return <xml><p>Count: {{[n]}}</p></xml>}}/>\n\
                    <button onclick={{fn _ => n <- get count; set count (n + 1)}}>+</button>\n\
                    <button onclick={{fn _ => n <- get count; set count (n - 1)}}>-</button>\n\
                    <button onclick={{fn _ => set count 0}}>Reset</button>\n\
                    </body>\n\
                    </xml>\n",
                        mod = mod_name
                    ),
                )?;
                std::fs::create_dir(format!("{}/style", name))?;
                std::fs::create_dir(format!("{}/style/scss", name))?;
                std::fs::create_dir(format!("{}/style/css", name))?;
                write_file(
                    &format!("{}/style/scss/main.scss", name),
                    "$primary: #3498db;\n\
$bg:      #f5f5f5;\n\
$text:    #333;\n\
\n\
body {\n\
  font-family: sans-serif;\n\
  background: $bg;\n\
  color: $text;\n\
  margin: 0;\n\
  padding: 2rem;\n\
}\n\
\n\
h1 {\n\
  color: $primary;\n\
  margin-bottom: 1rem;\n\
}\n\
\n\
button {\n\
  background: $primary;\n\
  color: white;\n\
  border: none;\n\
  padding: 0.5rem 1rem;\n\
  margin: 0.25rem;\n\
  cursor: pointer;\n\
  border-radius: 4px;\n\
  font-size: 1rem;\n\
\n\
  &:hover {\n\
    opacity: 0.85;\n\
  }\n\
}\n\
\n\
p {\n\
  font-size: 1.5rem;\n\
}\n",
                )?;
                write_file(
                    &format!("{}/style/css/main.css", name),
                    "body {\n\
  font-family: sans-serif;\n\
  background: #f5f5f5;\n\
  color: #333;\n\
  margin: 0;\n\
  padding: 2rem;\n\
}\n\
\n\
h1 {\n\
  color: #3498db;\n\
  margin-bottom: 1rem;\n\
}\n\
\n\
button {\n\
  background: #3498db;\n\
  color: white;\n\
  border: none;\n\
  padding: 0.5rem 1rem;\n\
  margin: 0.25rem;\n\
  cursor: pointer;\n\
  border-radius: 4px;\n\
  font-size: 1rem;\n\
}\n\
\n\
button:hover {\n\
  opacity: 0.85;\n\
}\n\
\n\
p {\n\
  font-size: 1.5rem;\n\
}\n",
                )?;
                write_file(
                    &format!("{}/urweb.toml", name),
                    &format!(
                        "[package]\nname = \"{n}\"\nkind = \"app\"\n\n\
[build]\nentry     = \"{n}\"\ndb        = \"sqlite\"\nccompiler = \"gcc\"\nboot      = false\n\n\
[style]\nscss = \"style/scss/main.scss\"\ncss  = \"style/css/main.css\"\n",
                        n = name
                    ),
                )?;
            }
            ProjectKind::Library => {
                write_file(&format!("{}/{}.urp", name, name), &format!("{}\n", name))?;
                write_file(
                    &format!("{}/{}.urs", name, name),
                    "val add : int -> int -> int\n\
val greet : string -> string\n",
                )?;
                write_file(
                    &format!("{}/{}.ur", name, name),
                    "fun add (x : int) (y : int) : int = x + y\n\
\n\
fun greet (name : string) : string = \"Hello, \" ^ name ^ \"!\"\n",
                )?;
                write_file(
                    &format!("{}/urweb.toml", name),
                    &format!(
                        "[package]\nname = \"{n}\"\nkind = \"lib\"\n\n\
[build]\nentry = \"{n}\"\nboot  = false\n",
                        n = name
                    ),
                )?;
            }
        }

        write_file(&format!("{}/cursor.md", name), CURSOR_MD)?;
        write_file(&format!("{}/claude.md", name), CLAUDE_MD)?;

        let gitignore = match kind {
            ProjectKind::App => format!("{}{}", GITIGNORE, GITIGNORE_APP_SUFFIX),
            ProjectKind::Library => GITIGNORE.to_string(),
        };
        write_file(&format!("{}/.gitignore", name), &gitignore)?;
        Ok(())
    })();

    if let Err(e) = result {
        eprintln!("error: {}", e);
        return 1;
    }

    // Attempt git init (failure is non-fatal)
    let git_ok = std::process::Command::new("git")
        .args(["-C", name, "init", "-q"])
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map_or(false, |s| s.success());

    let kind_str = match kind {
        ProjectKind::App => "app",
        ProjectKind::Library => "library",
    };

    let kind_specific = kind_specific_created_files(kind, name);
    println!("Created {} '{}'", kind_str, name);
    println!();
    println!("  {name}/{name}.urp");
    println!("  {name}/{name}.ur");
    for line in kind_specific {
        println!("  {line}");
    }
    println!("  {name}/urweb.toml");
    println!("  {name}/cursor.md");
    println!("  {name}/claude.md");
    println!("  {name}/.gitignore");
    println!();
    if git_ok {
        println!("  (initialized git repository)");
        println!();
    }
    println!("Build:  cd {name} && urweb build");

    0
}

// ---------------------------------------------------------------------------
// Subcommand: build
// ---------------------------------------------------------------------------

/// Simple TOML reader: returns `(key, value)` pairs.
fn parse_toml(content: &str) -> Vec<(String, String)> {
    let mut section = String::new();
    let mut entries = vec![];
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line.starts_with('[') && line.ends_with(']') {
            section = line[1..line.len() - 1].trim().to_string();
            continue;
        }
        if let Some(eq) = line.find('=') {
            let key = line[..eq].trim();
            let raw_val = line[eq + 1..].trim();
            let val = if raw_val.starts_with('"') && raw_val.ends_with('"') && raw_val.len() >= 2 {
                raw_val[1..raw_val.len() - 1].to_string()
            } else {
                raw_val.to_string()
            };
            let full_key = if section.is_empty() {
                key.to_string()
            } else {
                format!("{}.{}", section, key)
            };
            entries.push((full_key, val));
        }
    }
    entries
}

fn toml_get<'a>(entries: &'a [(String, String)], key: &str) -> Option<&'a str> {
    entries
        .iter()
        .find(|(k, _)| k == key)
        .map(|(_, v)| v.as_str())
}

fn is_lib_project(kind: &str) -> bool {
    kind == "lib"
}

fn parse_boot(value: &str) -> bool {
    value == "true"
}

fn sass_tool_available(has_sass: bool, has_sassc: bool) -> bool {
    has_sass || has_sassc
}

fn has_sass_or_sassc() -> bool {
    let has_sass = std::process::Command::new("which")
        .arg("sass")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map_or(false, |s| s.success());
    let has_sassc = std::process::Command::new("which")
        .arg("sassc")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map_or(false, |s| s.success());
    sass_tool_available(has_sass, has_sassc)
}

fn should_add_ccompiler(cc: &str) -> bool {
    !cc.is_empty()
}

fn command_succeeded(status: &std::io::Result<std::process::ExitStatus>) -> bool {
    status.as_ref().map_or(false, |s| s.success())
}

fn is_file_arg(arg: &str) -> bool {
    !arg.starts_with('-')
}

fn should_skip_urp_line(line: &str) -> bool {
    line.is_empty() || line.starts_with('#')
}

fn file_exists(path: &str) -> bool {
    std::path::Path::new(path).exists()
}

fn is_unknown_compiler_flag(flag: &str, arg: &str) -> bool {
    flag.is_empty() || arg.starts_with('-')
}

fn is_valid_limit(n: i32) -> bool {
    n >= 0
}

fn build_project() -> i32 {
    let toml_path = "urweb.toml";
    if !file_exists(toml_path) {
        eprintln!(
            "error: urweb.toml not found in current directory\n\
Run 'urweb new <name>' to create a project, then 'cd <name> && urweb build'"
        );
        return 1;
    }

    let toml_content = match std::fs::read_to_string(toml_path) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error reading urweb.toml: {}", e);
            return 1;
        }
    };
    let entries = parse_toml(&toml_content);

    let kind = toml_get(&entries, "package.kind").unwrap_or("app");
    let entry = toml_get(&entries, "build.entry").unwrap_or("");
    let db = toml_get(&entries, "build.db").unwrap_or("sqlite");
    let cc = toml_get(&entries, "build.ccompiler").unwrap_or("");
    let is_lib = is_lib_project(kind);
    let boot = parse_boot(toml_get(&entries, "build.boot").unwrap_or("false"));
    let scss = toml_get(&entries, "style.scss");
    let css = toml_get(&entries, "style.css");

    if entry.is_empty() {
        eprintln!("error: urweb.toml: [build] entry is required");
        return 1;
    }

    // Compile SCSS → CSS if configured
    if let (Some(scss_path), Some(css_path)) = (scss, css) {
        if has_sass_or_sassc() {
            let has_sass = std::process::Command::new("which")
                .arg("sass")
                .stdout(std::process::Stdio::null())
                .stderr(std::process::Stdio::null())
                .status()
                .map_or(false, |s| s.success());
            println!("  Compiling SCSS...");
            let sass_arg = format!("{}:{}", scss_path, css_path);
            let status = if has_sass {
                std::process::Command::new("sass")
                    .args([sass_arg.as_str(), "--no-source-map", "--style=expanded"])
                    .status()
            } else {
                std::process::Command::new("sassc")
                    .args([scss_path, css_path])
                    .status()
            };
            if !command_succeeded(&status) {
                eprintln!("error: SCSS compilation failed");
                return 1;
            }
        }
    }

    println!(
        "  {} {}...",
        if is_lib { "Type-checking" } else { "Building" },
        entry
    );

    // Build the argument list to pass to the compiler
    let mut args: Vec<String> = vec![];
    if should_add_ccompiler(cc) {
        args.extend(["-ccompiler".to_string(), cc.to_string()]);
    }
    if boot {
        args.push("-boot".to_string());
    }
    if is_lib {
        args.extend(["-tc".to_string(), entry.to_string()]);
    } else {
        args.extend([
            "-dbms".to_string(),
            db.to_string(),
            "-db".to_string(),
            format!("{}.db", entry),
            "-sql".to_string(),
            format!("{}.sql", entry),
            entry.to_string(),
        ]);
    }

    // Call the compiler pipeline (currently all stubs)
    run_compiler_args(&args)
}

// ---------------------------------------------------------------------------
// Subcommand: install
// ---------------------------------------------------------------------------

fn install_package(spec: &str) -> i32 {
    // Extract repo name from "author/repo" or just "repo"
    let repo_name = spec
        .split('/')
        .filter(|s| !s.is_empty())
        .last()
        .unwrap_or(spec);

    if !file_exists("urweb.toml") {
        eprintln!("error: urweb.toml not found; run from project directory");
        return 1;
    }

    // Ensure packages/ directory exists
    let _ = std::fs::create_dir("packages");

    // The spec may be "github:author/repo" or just "author/repo"
    let github_spec = if spec.contains(':') {
        spec.to_string()
    } else {
        format!("https://github.com/{}", spec)
    };

    let pkg_dir = format!("packages/{}", repo_name);
    if file_exists(&pkg_dir) {
        println!("Package '{}' already installed at {}", repo_name, pkg_dir);
        return 0;
    }

    println!("Installing {} ...", spec);
    let status = std::process::Command::new("git")
        .args(["submodule", "add", "--depth=1", &github_spec, &pkg_dir])
        .status();

    if !command_succeeded(&status) {
        eprintln!("error: git submodule add failed");
        return 1;
    }

    // Add the package's .urp path to urweb.toml (append to [build] section)
    let lib_urp = format!("packages/{}/{}", repo_name, repo_name);
    println!("Installed {} at {}", spec, pkg_dir);
    println!("Add to your .urp:  library {}", lib_urp);
    0
}

// ---------------------------------------------------------------------------
// Subcommand: fmt
// ---------------------------------------------------------------------------

fn fmt_command(args: &[String]) -> i32 {
    let mut check_mode = false;
    let mut _width: u32 = 80;
    let mut files: Vec<String> = vec![];
    let mut args_iter = args.iter();
    while let Some(arg) = args_iter.next() {
        let (flag, opt_val) = if let Some(eq) = arg.find('=') {
            let (f, v) = arg.split_at(eq);
            (f, Some(v[1..].to_string()))
        } else {
            (arg.as_str(), None)
        };
        match flag {
            "-help" | "--help" | "-h" => {
                println!("urweb fmt [options] [files...]");
                println!("  If no files: format all .ur/.urs in project (from urweb.toml)");
                println!("  Otherwise: format the given files.");
                println!("  -check, --check: check only; exit 1 if would reformat (CI mode)");
                println!("  -w N, --width N, --width=N: line width (default 80)");
                return 0;
            }
            "-check" | "--check" => {
                check_mode = true;
            }
            "-w" | "--width" => {
                if let Some(n) = opt_val
                    .or_else(|| args_iter.next().cloned())
                    .and_then(|s| s.parse::<u32>().ok())
                {
                    _width = n;
                }
            }
            f if is_file_arg(f) => {
                files.push(f.to_string());
            }
            other => {
                eprintln!("warning: unknown fmt flag: {}", other);
            }
        }
    }

    if files.is_empty() {
        // Project mode
        if !file_exists("urweb.toml") {
            eprintln!("error: urweb.toml not found; run from project directory or specify files");
            return 1;
        }
        let toml_content = match std::fs::read_to_string("urweb.toml") {
            Ok(s) => s,
            Err(e) => {
                eprintln!("error: {}", e);
                return 1;
            }
        };
        let entries = parse_toml(&toml_content);
        let entry = toml_get(&entries, "build.entry").unwrap_or("");
        if entry.is_empty() {
            eprintln!("error: urweb.toml: [build] entry is required");
            return 1;
        }
        // Discover .ur/.urs files from the .urp
        let urp_path = format!("{}.urp", entry);
        if !file_exists(&urp_path) {
            eprintln!("error: project .urp not found: {}", urp_path);
            return 1;
        }
        // Read source list from .urp (simple: lines that don't start with a directive keyword)
        if let Ok(content) = std::fs::read_to_string(&urp_path) {
            for line in content.lines() {
                let line = line.trim();
                if should_skip_urp_line(line) {
                    continue;
                }
                // Skip directive lines
                let directive_keywords = [
                    "database",
                    "sql",
                    "prefix",
                    "rewrite",
                    "file",
                    "library",
                    "link",
                    "ffi",
                    "effectful",
                    "benignEffectful",
                    "clientOnly",
                    "serverOnly",
                    "jsFunc",
                    "timeout",
                    "sigfile",
                    "debug",
                ];
                if directive_keywords.iter().any(|kw| line.starts_with(kw)) {
                    continue;
                }
                // Assume it's a module name
                let ur = format!("{}.ur", line);
                let urs = format!("{}.urs", line);
                if std::path::Path::new(&ur).exists() {
                    files.push(ur);
                }
                if std::path::Path::new(&urs).exists() {
                    files.push(urs);
                }
            }
        }
        if files.is_empty() {
            println!("no .ur or .urs files found");
            return 0;
        }
    }

    let mut all_ok = true;
    for f in &files {
        if !f.ends_with(".ur") && !f.ends_with(".urs") {
            eprintln!("error: {} is not a .ur or .urs file", f);
            all_ok = false;
            continue;
        }
        if !file_exists(f) {
            eprintln!("error: {} not found", f);
            all_ok = false;
            continue;
        }
        // Placeholder: formatter not yet implemented
        if check_mode {
            // In check mode, succeed silently (formatter not implemented)
            eprintln!("note: formatter not yet implemented; {} skipped", f);
        } else {
            eprintln!("note: formatter not yet implemented; {} skipped", f);
        }
    }
    if all_ok {
        0
    } else {
        1
    }
}

// ---------------------------------------------------------------------------
// Subcommand: daemon
// ---------------------------------------------------------------------------

const SOCKET_PATH: &str = ".urweb_daemon";

fn daemon_command(args: &[String]) -> i32 {
    match args.first().map(|s| s.as_str()) {
        Some("stop") => {
            let _ = std::fs::remove_file(SOCKET_PATH);
            println!("Daemon stopped.");
            0
        }
        Some("start") => {
            eprintln!("note: daemon not yet implemented");
            0
        }
        _ => {
            eprintln!("usage: urweb daemon [start|stop]");
            1
        }
    }
}

// ---------------------------------------------------------------------------
// Direct compiler invocation (flags + project name)
// ---------------------------------------------------------------------------

/// Parse flags and run the compiler on a project file.
fn run_compiler_args(args: &[String]) -> i32 {
    let mut settings = Settings::new();
    let mut project_file: Option<String> = None;
    let mut _tc_only = false;
    let mut _verbose = false;
    let mut _timing = false;
    let mut _dump_source = false;
    let mut _do_iflow = false;
    let mut _partial_build: Option<String> = None;

    let mut args_iter = args.iter();
    while let Some(arg) = args_iter.next() {
        let raw = arg.trim_start_matches('-');
        let (flag, opt_val) = if let Some(eq) = raw.find('=') {
            let (f, v) = raw.split_at(eq);
            (f, Some(v[1..].to_string()))
        } else {
            (raw, None)
        };
        match flag {
            "help" | "h" => {
                print_usage(&settings);
                return 0;
            }
            "version" | "V" => {
                println!("{}", VERSION_STRING);
                return 0;
            }
            "numeric-version" => {
                println!("{}", VERSION_STRING);
                return 0;
            }
            "print-ccompiler" => {
                println!("{}", settings.config_c_compiler);
                return 0;
            }
            "print-cinclude" => {
                println!("{}", settings.config_include);
                return 0;
            }
            "ccompiler" => {
                if let Some(cc) = opt_val.or_else(|| args_iter.next().cloned()) {
                    settings.config_c_compiler = cc;
                }
            }
            "protocol" => {
                if let Some(p) = opt_val.or_else(|| args_iter.next().cloned()) {
                    settings.protocol = p;
                }
            }
            "prefix" => {
                if let Some(p) = opt_val.or_else(|| args_iter.next().cloned()) {
                    settings.set_url_prefix(&p);
                }
            }
            "db" => {
                if let Some(db) = opt_val.or_else(|| args_iter.next().cloned()) {
                    settings.dbstring = Some(db);
                }
            }
            "dbms" => {
                if let Some(db) = opt_val.or_else(|| args_iter.next().cloned()) {
                    settings.dbms = db;
                }
            }
            "debug" => {
                settings.debug = true;
            }
            "verbose" => {
                _verbose = true;
            }
            "timing" => {
                _timing = true;
            }
            "tc" => {
                _tc_only = true;
            }
            "dumpSource" => {
                _dump_source = true;
            }
            "output" | "o" => {
                if let Some(f) = opt_val.or_else(|| args_iter.next().cloned()) {
                    settings.exe = Some(f);
                }
            }
            "sql" => {
                if let Some(f) = opt_val.or_else(|| args_iter.next().cloned()) {
                    settings.sql = Some(f);
                }
            }
            "endpoints" => {
                if let Some(f) = opt_val.or_else(|| args_iter.next().cloned()) {
                    settings.endpoints = Some(f);
                }
            }
            "static" => {
                settings.static_linking = true;
            }
            "boot" => {
                settings.boot_linking = true;
            }
            "sigfile" => {
                if let Some(f) = opt_val.or_else(|| args_iter.next().cloned()) {
                    settings.sig_file = Some(f);
                }
            }
            "iflow" => {
                _do_iflow = true;
            }
            "sqlcache" => {
                settings.sqlcache = true;
            }
            "disablesqlstructurecheck" => {
                settings.disable_sql_structure_check = true;
            }
            "moduleOf" => {
                if let Some(f) = opt_val.or_else(|| args_iter.next().cloned()) {
                    println!("{}", urweb::compiler::module_of(&f));
                }
                return 0;
            }
            "limit" => {
                let class = args_iter.next().cloned().unwrap_or_default();
                let num_str = args_iter.next().cloned().unwrap_or_default();
                match num_str.parse::<i32>() {
                    Ok(n) if is_valid_limit(n) => {
                        if let Err(e) = settings.add_limit(&class, n) {
                            eprintln!("error: {}", e);
                            return 1;
                        }
                    }
                    _ => {
                        eprintln!("error: invalid limit number '{}'", num_str);
                        return 1;
                    }
                }
            }
            "partialBuild" => {
                if let Some(m) = opt_val.or_else(|| args_iter.next().cloned()) {
                    _partial_build = Some(m);
                }
            }
            "startLspServer" => {
                eprintln!("note: LSP server not yet implemented");
                return 0;
            }
            "path" => {
                let _ = args_iter.next();
                let _ = args_iter.next();
            }
            "root" => {
                let _ = args_iter.next();
                let _ = args_iter.next();
            }
            other => {
                if is_unknown_compiler_flag(other, arg) {
                    eprintln!("error: unknown flag -{}", other);
                    return 1;
                }
                project_file = Some(arg.clone());
            }
        }
    }

    let project = match project_file {
        Some(p) => p,
        None => {
            eprintln!("error: no project specified, see -help");
            return 1;
        }
    };

    // Run the compilation pipeline
    eprintln!(
        "note: Rust compiler pipeline not yet implemented; \
please use the SML binary for actual compilation"
    );
    eprintln!("(would compile: {})", project);
    1
}

fn print_usage(_settings: &Settings) {
    let name = std::env::args().next().unwrap_or_else(|| "urweb".into());
    println!("usage:");
    println!("  {} new <project-name>", name);
    println!("  {} new --lib <project-name>", name);
    println!("  {} build", name);
    println!("  {} fmt [options] [files...]", name);
    println!("  {} install author/repo", name);
    println!("  {} daemon [stop|start]", name);
    println!("  {} [flag ...] project-name", name);
    println!("Standard options: -h, --help; -V, --version; -o, --output=FILE");
    println!("Supported flags include:");
    println!("  -h, -help, --help    print this overview");
    println!("  -V, -version         print version and exit");
    println!("  -ccompiler <prog>    set C compiler");
    println!("  -dbms <engine>       select database engine [sqlite|mysql|postgres]");
    println!("  -db <connstr>        database connection string");
    println!("  -prefix <prefix>     URL prefix");
    println!("  -sql <file>          output SQL DDL to <file>");
    println!("  -o, -output <file>    output executable to <file> (or --output=FILE)");
    println!("  -tc                  stop after type checking");
    println!("  -debug               save intermediate C files");
    println!("  -verbose             verbose output");
    println!("  -iflow               run information-flow analysis");
    println!("  -limit <class> <n>   set resource limit");
    println!("  -startLspServer      start LSP server");
    println!("  -moduleOf <file>     print module name of <file>");
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let code = dispatch(&args[1..]);
    process::exit(code);
}

fn dispatch(args: &[String]) -> i32 {
    match args.first().map(|s| s.as_str()) {
        None => {
            eprintln!("usage: urweb <command> [args...]");
            eprintln!("Run 'urweb -help' for more information.");
            1
        }
        Some("new") => {
            // urweb new [--lib] <name>
            let rest = &args[1..];
            if rest.first().map_or(false, |s| s == "--lib" || s == "-lib") {
                let name = rest.get(1).map(|s| s.as_str()).unwrap_or("");
                if name.is_empty() {
                    eprintln!("usage: urweb new --lib <name>");
                    return 1;
                }
                new_project(ProjectKind::Library, name)
            } else {
                let name = rest.first().map(|s| s.as_str()).unwrap_or("");
                if name.is_empty() {
                    eprintln!("usage: urweb new <name>");
                    return 1;
                }
                new_project(ProjectKind::App, name)
            }
        }
        Some("build") => build_project(),
        Some("install") => {
            let spec = args.get(1).map(|s| s.as_str()).unwrap_or("");
            if spec.is_empty() {
                eprintln!("usage: urweb install <author/repo>");
                1
            } else {
                install_package(spec)
            }
        }
        Some("fmt") => fmt_command(&args[1..]),
        Some("daemon") => daemon_command(&args[1..]),
        Some(_) => run_compiler_args(args),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    static CWD_LOCK: Mutex<()> = Mutex::new(());

    #[test]
    fn validate_name_empty() {
        assert!(validate_project_name("").is_err());
    }

    #[test]
    fn validate_name_starts_with_digit() {
        assert!(validate_project_name("1foo").is_err());
    }

    #[test]
    fn validate_name_valid() {
        assert!(validate_project_name("my_app").is_ok());
        assert!(validate_project_name("Foo123").is_ok());
    }

    #[test]
    fn validate_name_hyphen_invalid() {
        assert!(validate_project_name("my-app").is_err());
    }

    #[test]
    fn toml_parse_basic() {
        let content = "[build]\nentry = \"myapp\"\ndb = \"sqlite\"\n";
        let entries = parse_toml(content);
        assert_eq!(
            entries
                .iter()
                .find(|(k, _)| k == "build.entry")
                .map(|(_, v)| v.as_str()),
            Some("myapp")
        );
    }

    #[test]
    fn toml_parse_section_and_key() {
        let content = "[build]\nentry = \"x\"\n";
        let entries = parse_toml(content);
        assert_eq!(toml_get(&entries, "build.entry"), Some("x"));
    }

    #[test]
    fn toml_get_missing_returns_none() {
        let entries = parse_toml("[build]\nentry = \"x\"\n");
        assert_eq!(toml_get(&entries, "build.other"), None);
        assert_eq!(toml_get(&entries, "missing"), None);
    }

    #[test]
    fn toml_parse_empty_line_skipped() {
        let content = "[a]\n\nkey = \"v\"\n";
        let entries = parse_toml(content);
        assert_eq!(toml_get(&entries, "a.key"), Some("v"));
    }

    #[test]
    fn toml_parse_quoted_value() {
        let content = r#"[x]
k = "hello""#;
        let entries = parse_toml(content);
        assert_eq!(toml_get(&entries, "x.k"), Some("hello"));
    }

    #[test]
    fn toml_comment_ignored() {
        let content = "# comment\n[build]\nentry = \"x\"\n";
        let entries = parse_toml(content);
        assert_eq!(entries.len(), 1);
    }

    #[test]
    fn toml_line_looks_like_comment_not_parsed_as_key() {
        let content = "#key = value\n[build]\nentry = \"x\"\n";
        let entries = parse_toml(content);
        assert!(!entries.iter().any(|(k, _)| k.starts_with('#')));
        assert_eq!(toml_get(&entries, "build.entry"), Some("x"));
    }

    #[test]
    fn toml_section_bracket_requires_both() {
        let content = "[build\nentry = \"x\"\n";
        let entries = parse_toml(content);
        assert_eq!(toml_get(&entries, "entry"), Some("x"));
    }

    #[test]
    fn is_lib_project_detects_lib() {
        assert!(is_lib_project("lib"));
        assert!(!is_lib_project("app"));
        assert!(!is_lib_project(""));
    }

    #[test]
    fn parse_boot_detects_true() {
        assert!(parse_boot("true"));
        assert!(!parse_boot("false"));
        assert!(!parse_boot(""));
    }

    #[test]
    fn should_add_ccompiler_when_non_empty() {
        assert!(should_add_ccompiler("gcc"));
        assert!(!should_add_ccompiler(""));
    }

    #[test]
    fn is_file_arg_accepts_ur_without_dash() {
        assert!(is_file_arg("m.ur"));
        assert!(!is_file_arg("-check"));
    }

    #[test]
    fn should_skip_urp_line_empty_and_comments() {
        assert!(should_skip_urp_line(""));
        assert!(should_skip_urp_line("# comment"));
        assert!(!should_skip_urp_line("mymod"));
    }

    #[test]
    fn is_unknown_compiler_flag_detects_flags() {
        assert!(is_unknown_compiler_flag("", "-"));
        assert!(is_unknown_compiler_flag("bad", "-bad"));
        assert!(!is_unknown_compiler_flag("myproj", "myproj"));
    }

    #[test]
    fn is_valid_limit_non_negative() {
        assert!(is_valid_limit(0));
        assert!(is_valid_limit(1));
        assert!(!is_valid_limit(-1));
    }

    #[test]
    fn command_succeeded_ok_and_success() {
        let s = std::process::Command::new("true").status();
        assert!(command_succeeded(&s));
    }

    #[test]
    fn sass_tool_available_either_or() {
        assert!(sass_tool_available(true, false));
        assert!(sass_tool_available(false, true));
        assert!(sass_tool_available(true, true));
        assert!(!sass_tool_available(false, false));
    }

    #[test]
    fn file_exists_detects_present_and_absent() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let cwd = std::env::current_dir().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();
        std::fs::write("exists.txt", "").unwrap();
        assert!(file_exists("exists.txt"));
        assert!(!file_exists("nonexistent.txt"));
        std::env::set_current_dir(&cwd).unwrap();
    }

    #[test]
    fn command_succeeded_err_fails() {
        let s = std::process::Command::new("/nonexistent").status();
        assert!(!command_succeeded(&s));
    }

    #[test]
    fn toml_unclosed_quote_preserves_raw() {
        let content = "[x]\nk = \"hello\n";
        let entries = parse_toml(content);
        let v = toml_get(&entries, "x.k").unwrap();
        assert!(v.contains("hello"), "unclosed quote should not strip");
    }

    #[test]
    fn capitalize_helper() {
        assert_eq!(capitalize("hello"), "Hello");
        assert_eq!(capitalize(""), "");
        assert_eq!(capitalize("A"), "A");
    }

    #[test]
    fn kind_specific_created_files_app() {
        let files = kind_specific_created_files(ProjectKind::App, "foo");
        assert!(files.iter().any(|s| s.contains("style/scss")));
        assert!(!files.iter().any(|s| s.ends_with(".urs")));
    }

    #[test]
    fn kind_specific_created_files_library() {
        let files = kind_specific_created_files(ProjectKind::Library, "mylib");
        assert!(files.iter().any(|s| s.ends_with(".urs")));
        assert!(!files.iter().any(|s| s.contains("style/")));
    }

    #[test]
    fn dispatch_no_args() {
        assert_ne!(dispatch(&[]), 0);
    }

    #[test]
    fn new_project_rejects_empty_name() {
        assert_ne!(new_project(ProjectKind::App, ""), 0);
    }

    #[test]
    fn new_project_rejects_invalid_name() {
        assert_ne!(new_project(ProjectKind::App, "1foo"), 0);
    }

    #[test]
    fn new_project_creates_app() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let project_dir = dir.path().to_path_buf();
        let cwd = std::env::current_dir().unwrap();
        assert!(std::env::set_current_dir(&project_dir).is_ok());
        let code = new_project(ProjectKind::App, "proj_xyz");
        assert!(std::env::set_current_dir(&cwd).is_ok());
        assert_eq!(code, 0);
        let proj = project_dir.join("proj_xyz");
        assert!(
            proj.join("proj_xyz.urp").exists(),
            "{:?} should exist",
            proj
        );
        assert!(proj.join("proj_xyz.ur").exists());
        assert!(proj.join("style/scss/main.scss").exists());
        assert!(!proj.join("proj_xyz.urs").exists());
    }

    #[test]
    fn new_project_creates_library() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let project_dir = dir.path().to_path_buf();
        let cwd = std::env::current_dir().unwrap();
        assert!(std::env::set_current_dir(&project_dir).is_ok());
        let code = new_project(ProjectKind::Library, "mylib");
        assert!(std::env::set_current_dir(&cwd).is_ok());
        assert_eq!(code, 0);
        let proj = project_dir.join("mylib");
        assert!(proj.join("mylib.urs").exists());
        assert!(!proj.join("style/scss/main.scss").exists());
    }

    #[test]
    fn build_project_requires_urweb_toml() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let cwd = std::env::current_dir().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();
        let code = build_project();
        std::env::set_current_dir(&cwd).unwrap();
        assert_ne!(code, 0);
    }

    #[test]
    fn build_project_requires_entry() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let cwd = std::env::current_dir().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();
        std::fs::write("urweb.toml", "[package]\nname = \"x\"\n").unwrap();
        let code = build_project();
        std::env::set_current_dir(&cwd).unwrap();
        assert_ne!(code, 0);
    }

    #[test]
    fn build_project_with_valid_toml() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let cwd = std::env::current_dir().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();
        std::fs::write(
            "urweb.toml",
            "[package]\nname = \"t\"\n[build]\nentry = \"t\"\n",
        )
        .unwrap();
        std::fs::write("t.urp", "t.ur").unwrap();
        std::fs::write("t.ur", "val x = 1").unwrap();
        let code = build_project();
        std::env::set_current_dir(&cwd).unwrap();
        assert_eq!(code, 1);
    }

    #[test]
    fn fmt_command_urp_directives_skipped() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let cwd = std::env::current_dir().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();
        std::fs::write(
            "urweb.toml",
            "[package]\nname=\"x\"\n[build]\nentry=\"x\"\n",
        )
        .unwrap();
        std::fs::write("x.urp", "database sqlite\nmymod\n").unwrap();
        std::fs::write("mymod.ur", "val x = 1").unwrap();
        let args: Vec<String> = vec![];
        let code = fmt_command(&args);
        std::env::set_current_dir(&cwd).unwrap();
        assert_eq!(code, 0);
    }

    #[test]
    fn fmt_command_check_flag() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let cwd = std::env::current_dir().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();
        std::fs::write(
            "urweb.toml",
            "[package]\nname=\"x\"\n[build]\nentry=\"x\"\n",
        )
        .unwrap();
        std::fs::write("x.urp", "x.ur").unwrap();
        std::fs::write("x.ur", "val x = 1").unwrap();
        let args = vec!["-check".to_string()];
        let code = fmt_command(&args);
        std::env::set_current_dir(&cwd).unwrap();
        assert_eq!(code, 0);
    }

    #[test]
    fn fmt_command_width_arg_in_project_mode() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let cwd = std::env::current_dir().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();
        std::fs::write(
            "urweb.toml",
            "[package]\nname=\"x\"\n[build]\nentry=\"x\"\n",
        )
        .unwrap();
        std::fs::write("x.urp", "x.ur").unwrap();
        std::fs::write("x.ur", "val x = 1").unwrap();
        let args = vec!["-w".to_string(), "100".to_string()];
        let code = fmt_command(&args);
        std::env::set_current_dir(&cwd).unwrap();
        assert_eq!(
            code, 0,
            "-w 100 must parse width, not treat 100 as filename"
        );
    }

    #[test]
    fn install_requires_urweb_toml() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let cwd = std::env::current_dir().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();
        let code = install_package("author/pkg");
        std::env::set_current_dir(&cwd).unwrap();
        assert_ne!(code, 0);
    }

    #[test]
    fn install_already_installed_returns_zero() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let cwd = std::env::current_dir().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();
        std::fs::write("urweb.toml", "[package]\nname=\"x\"\n").unwrap();
        std::fs::create_dir_all("packages/mypkg").unwrap();
        let code = install_package("author/mypkg");
        std::env::set_current_dir(&cwd).unwrap();
        assert_eq!(
            code, 0,
            "install when package already present must return 0"
        );
    }

    #[test]
    fn daemon_stop_returns_zero() {
        let args = vec!["stop".to_string()];
        let code = daemon_command(&args);
        assert_eq!(code, 0);
    }

    #[test]
    fn daemon_no_arg_returns_nonzero() {
        let args: Vec<String> = vec![];
        let code = daemon_command(&args);
        assert_ne!(code, 0);
    }

    #[test]
    fn daemon_start_returns_zero() {
        let args = vec!["start".to_string()];
        let code = daemon_command(&args);
        assert_eq!(code, 0);
    }

    #[test]
    fn fmt_command_invalid_extension_returns_nonzero() {
        let args = vec!["foo.txt".to_string()];
        let code = fmt_command(&args);
        assert_ne!(code, 0);
    }

    #[test]
    fn fmt_command_nonexistent_file_returns_nonzero() {
        let args = vec!["nonexistent.ur".to_string()];
        let code = fmt_command(&args);
        assert_ne!(code, 0);
    }

    #[test]
    fn fmt_command_collects_ur_file_without_flag_prefix() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let cwd = std::env::current_dir().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();
        std::fs::write("m.ur", "val x = 1").unwrap();
        let args = vec!["m.ur".to_string()];
        let code = fmt_command(&args);
        std::env::set_current_dir(&cwd).unwrap();
        assert_eq!(
            code, 0,
            "m.ur (no -) must be collected as file, not treated as unknown flag"
        );
    }

    #[test]
    fn run_compiler_limit_invalid_returns_one() {
        let args = vec![
            "-limit".to_string(),
            "x".to_string(),
            "-1".to_string(),
            "proj".to_string(),
        ];
        let code = run_compiler_args(&args);
        assert_eq!(code, 1);
    }

    #[test]
    fn fmt_command_help_returns_zero() {
        let args = vec!["-help".to_string()];
        let code = fmt_command(&args);
        assert_eq!(code, 0);
    }

    #[test]
    fn run_compiler_help_returns_zero() {
        let args = vec!["-help".to_string()];
        let code = run_compiler_args(&args);
        assert_eq!(code, 0);
    }
}
